version: "3.8"

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recosante
    image: postgres:15.2
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbtest:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recosante_test
    image: postgres:15.2
    ports:
      - 5433:5432
    restart: always
    volumes:
      - pgdatatest:/var/lib/postgresql/data


  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    restart: always

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]



volumes:
  pgdata:
  pgdatatest:
