version: "3.9"
services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recosante
    image: postgres:15.2
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbtest:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recosante_test
    image: postgres:15.2
    ports:
      - 5433:5432
    restart: always
    volumes:
      - pgdatatest:/var/lib/postgresql/data

  flower:
    environment:
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_REDBEAT_REDIS_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      CELERY_TIMEZONE: "Europe/Paris"
      ENVIRONMENT: dev
      FLOWER_BASIC_AUTH: admin:admin
      TZ: "Europe/Paris"
    image: mher/flower:1.2
    ports:
      - 5555:5555
    restart: always

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    restart: always

  redis:
    image: redis:7.0.11
    ports:  
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  api:
    image: recosante-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - api/.env.docker

  frontend:
    image: recosante-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env.docker

  indice_pollution:
    image: recosante-indice_pollution
    build:
      context: libs/indice_pollution
    env_file:
      - libs/indice_pollution/.env.docker

volumes:
  pgdata:
  pgdatatest:
