apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-configmap
  namespace: recosante
spec:
  data:
    CELERY_BROKER_URL: "redis://redis:80"
    CELERY_RESULT_BACKEND: "redis://redis:80"
    CELERY_TIMEZONE: "Europe/Paris"
    TZ: "Europe/Paris"
