apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
  labels:
    application: recosante
    component: recosante
  name: recosante-check-newsletter-cronjob
  namespace: recosante
spec:
  schedule: 0 11 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: recosante
            component: recosante
          name: recosante-check-newsletter-cronjob
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
          containers:
            - image: ghcr.io/socialgouv/recosante/api:{{ .Values.global.imageTag }}
              imagePullPolicy: IfNotPresent
              name: recosante-check-newsletter
              command:
                - python
                - /code/check_newsletter.py
              securityContext:
                allowPrivilegeEscalation: false
              envFrom:
                - secretRef:
                    name: "{{ .Values.global.pgSecretName }}"
                - secretRef:
                    name: api-sealed-secret # for SIB key, todo: extract
              env:
                - name: DEBUG
                  value: "true"
                - name: SQLALCHEMY_DATABASE_URI
                  value: "$(DATABASE_URL)"
