apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: metabase-db-user
  namespace: recosante
spec:
  encryptedData:
    MB_ENCRYPTION_SECRET_KEY: AgBZKCCkCunJUyw3zO1qaHYYwgzAgG29pfGFf0gp6SxNrGePV3t1wpxa/KJ8S6HpXncTjLt40W8PGCmFa/ednr8P6YiIVWVWRcHSu0l0yT1p2UQ7n32BdeDd0NbNxfyC7TvCogEsd5o2KLZtYqJkdVcB5kGKeoSBCdGGLWbb+lC/PPLaZjmKybogCuQAqfiIWXXLQEC7Vdtxsj7goqAH3EzAJvm7Nnm7F1yCckNjlEu3jlbh9jIvhTdONel0JJIVJX1zidjdHwZeqYfNKo3MH4YLBC6cpgdEC0swcbRIxGzn9GHlahy7ZdeexA6O1ZRgTtZzifalm+HzQx18vULrKrzr2W2mEQIrSFoDxXbI2z9yBhb7ktuKcmAY/C8j2eUMbqsotJKJ2UojL7+H44Q7jD7zE0abtnoQVpfBo8PCsqQMlrTE7FQRbqpfOQeEQoxv5vneiQzhPakIgYGOzMDkrJne5/+RSRlbaE6k16FNC7WV97AKGsa/PwYQda8scaIkqz50/7ivEXlicmOez4SmNkf0NAtOS8M+ChCUdXXJN0GYkW1huy63hrwmdJqH7nGChMOrRV3ShE7aBPi1aSk4bQy9w0ioMCktPkVtafKQfKQg93Qaoed6R7Ggp0qM1GcMq0D4hRJc07ksxt+Ow1xX1Rw6nipZiM0znc1LLzXz/TW8Vlh3J5u6KCGHwNmWGp/FxKumrVoVb2TyFQROoiV3sIeacY2X5Ye1sBOv97pYk3jQXkXdFluJD5s=
  template:
    metadata:
    annotations:
      sealedsecrets.bitnami.com/namespace-wide: "true"
      name: metabase-db-user
    type: Opaque
