api-node:
  env:
    - name: ENVIRONMENT
      value: "development"
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-limit-memory: 3Gi    

cronjobs:
  env:
    - name: ENVIRONMENT
      value: "development"
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-limit-memory: 3Gi    

jobs:
  runs:
    
    run-unit-tests:
      ~needs: [api-node]
      checkout: true
      image: node:19-bullseye
      memoryLimit: 2Gi
      workingDir: /workspace/api-node
      run: |
        apt-get update && apt-get install -y python3 build-essential
        echo "🧪 tests unitaires - api-node"
        yarn install --immutable || (echo "yarn install failed for unit tests" && exit 1)
        yarn test:unit
        
    run-integration-tests:
      ~needs: [pg-api-node,api-node,run-unit-tests]
      checkout: true
      image: node:19-bullseye
      memoryLimit: 2Gi
      workingDir: /workspace/api-node
      envFrom:
        - secretRef:
            name: "pg-api-node-app"
      run: |
        apt-get update && apt-get install -y python3 build-essential
        echo "🧪 tests d'intégration - api-node"
        yarn install --immutable || (echo "yarn install failed for integration tests" && exit 1)
        echo "DATABASE_URL=$DATABASE_URL" > .env.test
        echo "NODE_ENV=test" >> .env.test
        yarn test:integration
