api:
  ~needs: [build-api, create-db]

indice:
  ~needs: [build-indice, create-db]

flower:
  ~needs: [redis]
  ~chart: app
  image: mher/flower:1.2
  containerPort: 5555
  probesPath: /dashboard
  envFrom:
    - secretRef:
        name: flower-sealed-secret
  env:
    - name: CELERY_BROKER_URL
      value: redis://redis:80
    - name: CELERY_RESULT_BACKEND
      value: redis://redis:80
    - name: CELERY_TIMEZONE
      value: Europe/Paris
    - name: FLOWER_PORT
      value: "5555"

jobs:
  runs:
    create-db:
      use: create-db
      with:
        useAzureFlex: "true"
