pg:
  ~chart: pg
  cnpg-cluster:
    annotations:
      oblik.socialgouv.io/min-request-cpu: 500m
      oblik.socialgouv.io/min-limit-cpu: "1"
      oblik.socialgouv.io/min-request-memory: 2Gi

api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, api]
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-limit-memory: 3Gi 

api-node:
  env:
    - name: ENVIRONMENT
      value: "development"
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-limit-memory: 3Gi    

cronjobs:
  env:
    - name: ENVIRONMENT
      value: "development"
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-limit-memory: 3Gi    

jobs:
  runs:
    seed-db:
      ~needs: [pg]
      retry: 3
      checkout: true
      image: ghcr.io/socialgouv/docker/psql:7.0.0
      envFrom:
        - secretRef:
            name: "pg-app"
      run: |
        if [[ $(psql -c "\dt public.alembic_version") ]]
        then
            echo "Data already loaded"
        else
            echo "Init database"
            psql -b < /workspace/seeds.sql
        fi

    launch-celery-tasks:
      # launch all celery tasks immediately in dev to start refreshing data
      # and not wait for the hourly cron
      ~needs: [indice]
      checkout: false
      kubernetes: true
      image: bitnami/kubectl
      run: |
        indice_pod=$(kubectl get pods -o name -n {{ .Values.global.namespace }}  | grep pod/indice)
        kubectl exec $indice_pod -n {{ .Values.global.namespace }} -- .venv/bin/python call_all_tasks.py
        
    run-unit-tests:
      ~needs: [api-node]
      checkout: true
      image: node:19
      workingDir: /workspace/api-node
      run: |
        echo "🧪 tests unitaires - api-node"
        yarn 
        yarn test:unit
        
    run-integration-tests:
      ~needs: [api-node, pg, run-unit-tests]
      checkout: true
      image: node:19
      workingDir: /workspace/api-node
      envFrom:
        - secretRef:
            name: "pg-app"
      run: |
        echo "🧪 tests d'intégration - api-node"
        yarn 
        echo "DATABASE_URL=$DATABASE_URL" > .env.test
        echo "NODE_ENV=test" >> .env.test
        yarn prisma-setup-test
        yarn test:integration
