api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, seed-db]

jobs:
  runs:
    create-db:
      use: create-db
      with:
        useAzureFlex: "true"
    seed-db:
      use: seed-db
      ~needs: [create-db]
      with:
        seedPath: ./seeds.sql
