api:
  ~needs: [build-api, create-db]

indice:
  ~needs: [build-indice, create-db]

flower:
  ~needs: [redis]
  ~chart: app
  image: mher/flower:1.2
  containerPort: 8080
  envFrom:
    - secretRef:
        name: flower-sealed-seacret
  env:
    - name: CELERY_BROKER_URL
      value: http://redis:80
    - name: CELERY_RESULT_BACKEND
      value: http://redis:80
    - name: CELERY_TIMEZONE
      value: Europe/Paris
    - name: PORT
      value: "8080"

jobs:
  runs:
    create-db:
      use: create-db
      with:
        useAzureFlex: "true"
