global:
  pgSecretName: pg-app

pg:
  ~chart: pg

api:
  ~needs: [build-api, pg]

indice:
  ~needs: [build-indice, api]

# jobs:
#   runs:
#     seed-db:
#       use: seed-db
#       ~needs: [pg]
#       with:
#         seedPath: ./seeds.sql
