global:
  pgSecretName: pg-app

pg:
  ~chart: pg
  cnpg-cluster:
    postgresqlParameters:
      work_mem: 512MB

api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, api]

jobs:
  runs:
    seed-db:
      ~needs: [pg]
      retry: 3
      checkout: true
      image: ghcr.io/socialgouv/docker/psql:7.0.0
      envFrom:
        - secretRef:
            name: "{{ $.Values.global.pgSecretName }}"
      run: |
        if [[ $(psql -c "\dt public.alembic_version") ]]
        then
            echo "Data already loaded"
        else
            echo "Init database"
            psql -b < /workspace/seeds.sql
        fi

    launch-celery-tasks:
      # launch all celery tasks immediately in dev to start refreshing data
      # and not wait for the hourly cron
      ~needs: [indice]
      checkout: false
      kubernetes: true
      image: bitnami/kubectl
      run: |
        indice_pod=$(kubectl get pods -o name  | grep indice)
        kubectl exec $pod -- .venv/bin/python call_all_tasks.py

