api:
  ~needs: [build-api, create-db]

indice_pollution:
  ~needs: [build-indice_pollution, create-db]

jobs:
  runs:
    create-db:
      use: create-db
      with:
        useAzureFlex: "true"
        pgAdminUserSecretRefName: azure-pg-admin
