api:
  ~needs: [build-api, create-db, seed-db]

indice:
  ~needs: [build-indice, create-db]


jobs:
  runs:
    create-db:
      use: create-db
      with:
        useAzureFlex: "true"
    seed-db:
      use: seed-db
      needs: [create-db]
      with:
        seedPath: ./api/seed-public_recommandations.sql
