global:
  pgSecretName: pg-app

pg:
  ~chart: pg

api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, seed-db]

jobs:
  runs:
    seed-db:
      use: seed-db
      ~needs: [pg]
      with:
        seedPath: ./seeds.sql
