global:
  pgSecretName: pg-app

pg:
  ~chart: pg
  cnpg-cluster:
    postgresqlParameters:
      work_mem: 512MB
    monitoring:
      ~tpl~enablePodMonitor: "true"


api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, api]

jobs:
  runs:
    seed-db:
      use: seed-db
      ~needs: [pg]
      with:
        seedPath: ./seeds.sql
