global:
  pgSecretName: pg-app

pg:
  ~chart: pg

api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, api]
  startupProbe:
    initialDelaySeconds: 900
    failureThreshold: 50
    periodSeconds: 10

jobs:
  runs:
    seed-db:
      use: seed-db
      ~needs: [pg]
      with:
        seedPath: ./seeds.sql
