global:
  pgSecretName: pg-app

pg:
  ~chart: pg
  cnpg-cluster:
    postgresqlParameters:
      work_mem: 512MB
      # synchronous_commit: "off"
      # commit_delay: "100000" # microseconds
    monitoring:
      ~tpl~enablePodMonitor: "true"

api:
  ~needs: [build-api, seed-db]

indice:
  ~needs: [build-indice, api]

jobs:
  runs:
    seed-db:
      ~needs: [pg]
      retry: 3
      checkout: true
      image: ghcr.io/socialgouv/docker/psql:7.0.0
      envFrom:
        - secretRef:
            name: "{{ $.Values.global.pgSecretName }}"
      run: |
        if [[ $(psql -c "\dt public.alembic_version") ]]
        then
            echo "Data already loaded"
        else
            echo "Init database"
            psql -b < /workspace/seeds.sql
        fi
        

