apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: flower-sealed-secret
spec:
  encryptedData:
    FLOWER_BASIC_AUTH: AgASMmkaX93nicg3Ugu8i3+t7B7VcXyB028NWTo1WCDKZQtrtwRrNV0fnNB5y7EQPuSY137SjGmuwdblX9rsi6VfebX6qzUx7PUocT+qxTVqQcux9ScxTguPpu75B8qgTC0kBasZLZUuHE/BbW4h8UhOyRbAp5Xd2PvKchpZDSiSgeMRJjggcmRJw3bIka1DuMamPILAKaiqkrcK1NNdTALu7WpblUi58+QOYwzosaIMTmUsv+DJ1RjZxQltAJ1OzvM/7lg6i8Rj0VJL21FLdhh0I7WBfOxYl9rkk4eBi5Yhk/E2edeRRudq+9UQiLZWiEqWbJLzeYp0YZNcj66Jz/tACYy6QCTH7HlanqguQ1mS0ESUNN7W/qb60zWwt5iYiYmcBTEMYKJBxDUz9nnQaHLtzHJb3X7iXE/HAD85hxi3D06sVz0yNXMn8FgDBfxt0tZydNMSIjpdn+BXiMLYEDZoZEy9Y7+vANT2E1QABmd4Ys+6eG0A3sCuJTuHwPHAXVR1kVfPUFSi1AchGEY6NwhFSmqon3Vs9ODE76y7ODDknblrfdXyhpUX31Ba+/SFcFpTrZqjcC2Fi3sw1BOW9/u4v9pBPDVCEk0O5OxCHrwIhr0WOGSKJnAdiMgIrZtx0KAtioGhTjw2L742FepH7LpdHv8QJTLoqmZpKlah85sR2P1j7iGv5+nI/em+Dk0bQdkywLwtGaAPcYJsX0ZnoJPVzD0n0fGz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: flower-sealed-secret
    type: Opaque
