global:
  host: "recosante.beta.gouv.fr"
  apiHost: "api.recosante.beta.gouv.fr"

pg:
  ~chart: pg
  cnpg-cluster:
    persistence:
      size: "50Gi"
    resources:
      requests:
        memory: 512Mi

flower:
  replicas: 1
  host: "flower-recosante.fabrique.social.gouv.fr"

redis:
  addVolumes:
    - redis
  volumeMounts:
    - name: redis
      mountPath: /data

api:
  replicas: 1

frontend:
  certSecretName: frontend-beta

indice:
  replicas: 1
