global:
  host: "recosante.beta.gouv.fr"
  apiHost: "api.recosante.beta.gouv.fr"
  apiNodeHost: "recosante-api-node.fabrique.social.gouv.fr"

pg:
  ~chart: pg
  backup:
    name: ovh # backup on a new folder
  cnpg-cluster:
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://recosante-prod-backups/recosante"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "recosante-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "recosante-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "recosante-prod-backups-access-key"
            key: bucket_region
    persistence:
      size: "50Gi"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi

pg-api-node:
  cnpg-cluster:
    persistence:
      size: "50Gi"

flower:
  replicas: 1
  host: "flower-recosante.fabrique.social.gouv.fr"

redis:
  addVolumes:
    - redis
  volumeMounts:
    - name: redis
      mountPath: /data

api:
  replicas: 1

api-node:
  resources:
    requests:
      cpu: 300m
      memory: 600Mi
    limits:
      cpu: 400m
      memory: 800Mi

frontend:
  resources:
    requests:
      cpu: 200m
      memory: 400Mi
    limits:
      cpu: 300m
      memory: 600Mi

frontend-next:
  certSecretName: frontend-beta

indice:
  replicas: 1
