global:
  host: "recosante.beta.gouv.fr"
  apiHost: "api.recosante.beta.gouv.fr"

flower:
  replicas: 1
  host: "flower-recosante.fabrique.social.gouv.fr"

redis:
  addVolumes:
    - redis
  volumeMounts:
    - name: redis
      mountPath: /data

api:
  replicas: 1

frontend:
  certSecretName: frontend-beta

indice:
  replicas: 1
  addVolumes:
    - meteofrance
  env:
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"
    - name: FS_BUCKET_URL
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: REMOTE_SERVER
    - name: FS_BUCKET_USERNAME
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: USERNAME
    - name: FS_BUCKET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: PASSWORD
