global:
  apiUrl: "https://api-recosante.fabrique.social.gouv.fr"
#
#frontend:
#  host: "https://recosante.beta.gouv.fr"

flower:
  replicas: 1

api:
  replicas: 1

indice:
  replicas: 1
  addVolumes:
    - meteofrance
  env:
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"
    - name: FS_BUCKET_URL
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: REMOTE_SERVER
    - name: FS_BUCKET_USERNAME
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: USERNAME
    - name: FS_BUCKET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: PASSWORD
