global:
  host: "recosante.beta.gouv.fr"
  apiHost: "api.recosante.beta.gouv.fr"
  apiNodeHost: "api-node.recosante.beta.gouv.fr"
  pgSecretName: pg-app

pg:
  ~chart: pg
  cnpg-cluster:
    persistence:
      size: "50Gi"
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 3Gi

pg-metabase:
  ~chart: pg

metabase:
  enabled: true
  ingress:
    enabled: false
  env:
    - name: MB_DB_CONNECTION_URI
      value: "postgres://$(PGHOST):5432/$(PGDATABASE)?user=$(PGUSER)&password=$(PGPASSWORD)&ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory"
  envFrom:
    - configMapRef:
        name: metabase-configmap
    - secretRef:
        name: pg-metabase-app

oauth2-proxy:
  host: "metabase-recosante.fabrique.social.gouv.fr"
  enabled: true
  upstream: http://metabase
  envFrom:
    - configMapRef:
        name: oauth2-proxy-configmap
    - secretRef:
        name: oauth2-proxy-sealed-secret
  additionalArgs:
    - --skip-auth-route
    - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*

flower:
  replicas: 1
  host: "flower-recosante.fabrique.social.gouv.fr"

redis:
  addVolumes:
    - redis
  volumeMounts:
    - name: redis
      mountPath: /data

api:
  replicas: 1

frontend:
  certSecretName: frontend-beta

indice:
  replicas: 1
