global:
  apiUrl: "https://api-recosante.fabrique.social.gouv.fr"
#
#frontend:
#  host: "https://recosante.beta.gouv.fr"

indice:
  addVolumes:
    - meteofrance
  volumeMounts:
    - mountPath: /meteofrance
      name: meteofrance
