global:
  host: "recosante.beta.gouv.fr"
  apiHost: "api.recosante.beta.gouv.fr"
  apiNodeHost: "recosante-api-node.fabrique.social.gouv.fr"


pg-api-node:
  cnpg-cluster:
    persistence:
      size: "100Gi"
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1500m
        memory: 3Gi

      
redis:
  strategyType: Recreate # mandatory because volume is RWO
  addVolumes:
    - redis
  volumeMounts:
    - name: redis
      mountPath: /data
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 256Mi
      

api-node:
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: 300m
      memory: 1Gi


frontend-next:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 786Mi
  autoscaler:
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
