"""created_at and updated_at

Revision ID: e6bd21eb460d
Revises: 64254d2cc72b
Create Date: 2023-09-21 15:37:35.257001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6bd21eb460d'
down_revision = '64254d2cc72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indice_history', schema='indice_schema')
    op.drop_table('episode_history', schema='indice_schema')
    op.add_column('commune', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('commune', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('departement', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('departement', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('epci', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('epci', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('episode_pollution', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('episode_pollution', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('indiceATMO', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('indiceATMO', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('indice_uv', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('indice_uv', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('potentiel_radon', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('potentiel_radon', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('raep', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('raep', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('region', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('region', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('vigilance_meteo', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('vigilance_meteo', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.create_unique_constraint(None, 'vigilance_meteo', ['zone_id', 'phenomene_id', 'date_export', 'validity'], schema='indice_schema')
    op.add_column('zone', sa.Column('created_at', sa.DateTime(), nullable=True), schema='indice_schema')
    op.add_column('zone', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='indice_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'updated_at', schema='indice_schema')
    op.drop_column('zone', 'created_at', schema='indice_schema')
    op.drop_constraint(None, 'vigilance_meteo', schema='indice_schema', type_='unique')
    op.drop_column('vigilance_meteo', 'updated_at', schema='indice_schema')
    op.drop_column('vigilance_meteo', 'created_at', schema='indice_schema')
    op.drop_column('region', 'updated_at', schema='indice_schema')
    op.drop_column('region', 'created_at', schema='indice_schema')
    op.drop_column('raep', 'updated_at', schema='indice_schema')
    op.drop_column('raep', 'created_at', schema='indice_schema')
    op.drop_column('potentiel_radon', 'updated_at', schema='indice_schema')
    op.drop_column('potentiel_radon', 'created_at', schema='indice_schema')
    op.drop_column('indice_uv', 'updated_at', schema='indice_schema')
    op.drop_column('indice_uv', 'created_at', schema='indice_schema')
    op.drop_column('indiceATMO', 'updated_at', schema='indice_schema')
    op.drop_column('indiceATMO', 'created_at', schema='indice_schema')
    op.drop_column('episode_pollution', 'updated_at', schema='indice_schema')
    op.drop_column('episode_pollution', 'created_at', schema='indice_schema')
    op.drop_column('epci', 'updated_at', schema='indice_schema')
    op.drop_column('epci', 'created_at', schema='indice_schema')
    op.drop_column('departement', 'updated_at', schema='indice_schema')
    op.drop_column('departement', 'created_at', schema='indice_schema')
    op.drop_column('commune', 'updated_at', schema='indice_schema')
    op.drop_column('commune', 'created_at', schema='indice_schema')
    op.create_table('episode_history',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('indice_schema.episode_history_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date_', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('code_zone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('polluant', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='episode_history_pkey'),
    schema='indice_schema'
    )
    op.create_table('indice_history',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('indice_schema.indice_history_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date_', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('insee', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='indice_history_pkey'),
    schema='indice_schema'
    )
    # ### end Alembic commands ###
