pg-api-node:
  ~chart: pg
  backup:
    name: 2023-03-06-11-56 # backup on a new folder
  cnpg-cluster:
    persistence:
      size: "22Gi"


api-node:
  env:
    - name: ENVIRONMENT
      value: "preproduction"

cronjobs:
  env:
    - name: ENVIRONMENT
      value: "preproduction"
