pg:
  ~chart: pg
  backup:
    name: 2023-02-27-14-34 # backup on a new folder
  cnpg-cluster:
    persistence:
      size: "20Gi"

pg-api-node:
  ~chart: pg
  backup:
    name: 2023-03-06-11-56 # backup on a new folder
  cnpg-cluster:
    persistence:
      size: "20Gi"

api:
  ~needs: [build-api, seed-db]


api-node:
  env:
    - name: ENVIRONMENT
      value: "preproduction"

cronjobs:
  env:
    - name: ENVIRONMENT
      value: "preproduction"


jobs:
  runs:
    seed-db:
      ~needs: [pg]
      retry: 3
      checkout: true
      image: ghcr.io/socialgouv/docker/psql:7.0.0
      envFrom:
        - secretRef:
            name: "pg-app"
      run: |
        if [[ $(psql -c "\dt public.alembic_version") ]]
        then
            echo "Data already loaded"
        else
            echo "Init database"
            psql -b < /workspace/seeds.sql
        fi

    launch-celery-tasks:
      # launch all celery tasks immediately in dev to start refreshing data
      # and not wait for the hourly cron
      ~needs: [indice]
      checkout: false
      kubernetes: true
      image: bitnami/kubectl
      run: |
        indice_pod=$(kubectl get pods -o name -n {{ .Values.global.namespace }}  | grep pod/indice)
        kubectl exec $indice_pod -n {{ .Values.global.namespace }} -- .venv/bin/python call_all_tasks.py
