import { type Config } from 'tailwindcss';
import formsPlugin from '@tailwindcss/forms';
import headlessuiPlugin from '@headlessui/tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-indiceuv-0',
    'bg-indiceuv-1',
    'bg-indiceuv-2',
    'bg-indiceuv-3',
    'bg-indiceuv-4',
    'bg-indiceuv-5',
    'bg-indiceuv-6',
    'bg-indiceuv-7',
    'bg-indiceuv-8',
    'bg-indiceuv-9',
    'bg-indiceuv-10',
    'bg-indiceuv-11',
    'stroke-indiceuv-0',
    'stroke-indiceuv-1',
    'stroke-indiceuv-2',
    'stroke-indiceuv-3',
    'stroke-indiceuv-4',
    'stroke-indiceuv-5',
    'stroke-indiceuv-6',
    'stroke-indiceuv-7',
    'stroke-indiceuv-8',
    'stroke-indiceuv-9',
    'stroke-indiceuv-10',
    'stroke-indiceuv-11',
    'bg-baignades-0',
    'bg-baignades-1',
    'bg-baignades-2',
    'stroke-baignades-0',
    'stroke-baignades-1',
    'stroke-baignades-2',
    'bg-radon-1',
    'bg-radon-2',
    'bg-radon-3',
    'fill-radon-1',
    'fill-radon-2',
    'fill-radon-3',
  ],
  theme: {
    fontFamily: {
      app: ['var(--font-marianne)'],
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.5rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      lg: ['1.125rem', { lineHeight: '2rem' }],
      xl: ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['2rem', { lineHeight: '3rem' }],
      '4xl': ['2.5rem', { lineHeight: '3rem' }],
      '5xl': ['3rem', { lineHeight: '1.1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    extend: {
      animation: {
        scroll:
          'scroll var(--animation-duration, 40s) var(--animation-direction, forwards) linear infinite',
        'fade-in': 'fade-in 0.5s linear forwards',
        marquee: 'marquee var(--marquee-duration) linear infinite',
        'spin-slow': 'spin 4s linear infinite',
        'spin-slower': 'spin 6s linear infinite',
        'spin-reverse': 'spin-reverse 1s linear infinite',
        'spin-reverse-slow': 'spin-reverse 4s linear infinite',
        'spin-reverse-slower': 'spin-reverse 6s linear infinite',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      colors: {
        muted: '#555555',
        'muted-100': '#9C9C9C',
        dark: '#232323',
        app: {
          green: '#4FCBAD',
          gray: '#ECF1FB',
          'gray-100': '#AEB1B7',
          'gray-300': '#D9D9EF',
          yellow: '#F2D072',
          primary: '#3343BD',
          dark: '#000A8B',
          50: '#f1f4ff',
          100: '#e5e8ff',
          200: '#ced5ff',
          300: '#a7b1ff',
          400: '#767fff',
          500: '#3f42ff',
          600: '#2118ff',
          700: '#1007fa',
          800: '#0d05d2',
          900: '#0c06ac',
          950: '#000091', // this is the main color
        },
        'raep-1': '#A1D05D',
        'raep-2': '#E3B23C',
        'raep-3': '#E18B46',
        'raep-4': '#E1644A',
        'raep-5': '#D44A4A',
        'vigilancemeteo-0': '#00B050',
        'vigilancemeteo-1': '#FFCC00',
        'vigilancemeteo-2': '#FF6600',
        'vigilancemeteo-3': '#CC0000',
        'indiceuv-0': '#4FCBAD',
        'indiceuv-1': '#4FCBAD',
        'indiceuv-2': '#4FCBAD',
        'indiceuv-3': '#F2D072',
        'indiceuv-4': '#F2D072',
        'indiceuv-5': '#F2D072',
        'indiceuv-6': '#E18B46',
        'indiceuv-7': '#E18B46',
        'indiceuv-8': '#E1644A',
        'indiceuv-9': '#E1644A',
        'indiceuv-10': '#E1644A',
        'indiceuv-11': '#D44A4A',
        'baignades-0': '#4FCBAD',
        'baignades-1': '#F2D072',
        'baignades-2': '#E1644A',
        'radon-1': '#4ba249',
        'radon-2': '#EF8541',
        'radon-3': '#cc0100',
      },
      fontFamily: {
        sans: 'var(--font-inter)',
      },
      keyframes: {
        scroll: {
          to: {
            transform: 'translate(calc(-50% - 0.5rem))',
          },
        },
        'fade-in': {
          from: {
            opacity: '0',
          },
          to: {
            opacity: '1',
          },
        },
        marquee: {
          '100%': {
            transform: 'translateY(-50%)',
          },
        },
        'spin-reverse': {
          to: {
            transform: 'rotate(-360deg)',
          },
        },
      },
      maxWidth: {
        '2xl': '40rem',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [
    formsPlugin,
    headlessuiPlugin,
    require('@tailwindcss/aspect-ratio'),
  ],
} satisfies Config;
