export enum RouteEnum {
  INDICATOR_SCENE = 'INDICATOR_SCENE',
  INDICATORS_LIST = 'INDICATORS_LIST',
  SETTINGS = 'SETTINGS',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
  ONBOARDING_GEOLOCATION = 'ONBOARDING_GEOLOCATION',
  SHARE = 'SHARE',
}
