export enum RouteEnum {
  INDICATOR_SCENE = 'INDICATOR_SCENE',
  INDICATORS_LIST = 'INDICATORS_LIST',
  SETTINGS = 'SETTINGS',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
  ONBOARDING_GEOLOCATION = 'ONBOARDING_GEOLOCATION',
  SHARE = 'SHARE',
}

export enum OnboardingRouteEnum {
  SCREEN_1 = 'SCREEN_1',
  SCREEN_2 = 'SCREEN_2',
  SCREEN_3 = 'SCREEN_3',
  SCREEN_4 = 'SCREEN_4',
  SCREEN_5 = 'SCREEN_5',
}
