export enum RouteEnum {
  DASHBOARD = 'DASHBOARD',
  INDICATORS_LIST = 'INDICATORS_LIST',
  SETTINGS = 'SETTINGS',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
  LOCATION = 'LOCATION',
  SHARE = 'SHARE',
}

export enum OnboardingRouteEnum {
  WELCOME = 'WELCOME',
  GEOLOCATION = 'GEOLOCATION',
  NOTIFICATIONS = 'NOTIFICATIONS',
}
