ciNamespace: ci-recosante

dependencies:
  fabrique:
    extends:
    - name: ovh
      ifEnv: [dev,preprod]
    - name: buildkit-service
      ifEnv: [dev,preprod]
  contrib:
    preDeploy:
      importSecrets:
        options:
          secrets:
            recosante-dev-backups-access-key: