projectName: recosante
ciNamespace: ci-reconsante
dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                pg-admin-user:
                  from: azure-pg-admin
