ciNamespace: ci-recosante

dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    dependencies:
      preDeploy:
        importSecrets:
          options:
            secrets:
              pg-admin-user:
                from: azure-pg-admin
                env: dev
                required: true
