ciNamespace: ci-recosante

dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                azure-pg-admin:
                  from: azure-pg-admin
                  env: dev
                  required: true
