projectName: recosante
ciNamespace: ci-recosante

dependencies:
  fabrique:
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                recosante-dev-backups-access-key:
                recosante-prod-backups-access-key:
