projectName: recosante
ciNamespace: ci-recosante

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev]
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                recosante-dev-backups-access-key:
                recosante-prod-backups-access-key:
