api: 
  ~chart: app
  ~needs: [build-api]
  imagePackage: api
  host: "api-{{ .Values.global.host }}"
  probesPath: /healthz
  containerPort: 3000
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1.5
      memory: 2Gi
  # envFrom:
  #   - secretRef:
  #       name: "{{ .Values.global.pgSecretName }}"
  #   - secretRef:
  #       name: backend-sealed-secret
  #   - configMapRef:
  #       name: backend-configmap
  env:
    - name: TZ
      value: Europe/Paris


jobs:
  ~chart: jobs
  runs:
    build-api:
      use: build
      with:
        imagePackage: api
        dockerfile: api/Dockerfile
