global:
  apiHost: "api-{{ .Values.global.host }}"
  apiNodeHost: "api-node-{{ .Values.global.host }}"
  pgApiNodeSecretName: "pg-api-node-app"

api-node:
  ~chart: app
  ~needs: [pg-api-node]
  containerPort: 3000
  imagePackage: api-node
  host: "{{ tpl .Values.global.apiNodeHost . }}"
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgApiNodeSecretName }}"
    - secretRef:
        name: api-node-sealed-secret
  annotations:
    oblik.socialgouv.io/min-request-cpu: 300m
    oblik.socialgouv.io/min-limit-cpu: 300m

frontend-next:
  ~chart: app
  probesPath: /healthz
  imagePackage: frontend-next
  host: "{{ .Values.global.host }}"



redis:
  ~chart: redis
  enabled: true
  ingress:
    enabled: false
  ~forceRestart: false



pg-api-node:
  ~chart: pg

cronjobs:
  ~chart: daemon
  ~needs: [pg-api-node]
  imagePackage: api-node
  replicas: 1
  entrypoint: ["yarn", "start-cronjobs"]
  envFrom:
    - secretRef:
        name: "pg-api-node-app"
    - secretRef:
        name: api-node-sealed-secret
