api:
  ~chart: app
  ~needs: [build-api]
  imagePackage: api
  host: "api-{{ .Values.global.host }}"
  probesPath: /healthz
  containerPort: 3000
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 1.5
      memory: 2Gi
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: api-sealed-secret
  env:
    - name: FLASK_APP
      value: ecosante
    - name: FLASK_DEBUG
      value: "false"
    - name: FLASK_ENV
      value: dev
    - name: DEBUG
      value: "true"
    - name: NODE_SASS_BIN
      value: "./yarn-scss"
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"

frontend:
  ~chart: app
  ~needs: [build-frontend]
  imagePackage: frontend
  host: "{{ .Values.global.host }}"
  containerPort: 8080
  resources:
    requests:
      cpu: 0.05
      memory: 64Mi
    limits:
      cpu: 0.5
      memory: 256Mi

indice_pollution:
  ~chart: app
  ~needs: [build-indice_pollution]
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: indice_pollution-sealed-secret
  env:
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"

redis:
  ~chart: redis
  enabled: true
  ingress:
    enabled: false

jobs:
  runs:
    build-api:
      use: build
      with:
        imagePackage: api
        context: api
    build-indice_pollution:
      use: build
      with:
        imagePackage: indice_pollution
        context: indice_pollution
    build-frontend:
      use: build
      with:
        imagePackage: frontend
        context: frontend
        buildArgs:
          GATSBY_API_BASE_URL: "api-{{ .Values.global.host }}"
          GATSBY_IFRAME_ID: some-id
          GATSBY_URL: "{{ .Values.global.host }}"
          GATSBY_REPOSITORY_URL: https://github.com/socialgouv/recosante
