global:
  apiHost: "api-{{ .Values.global.host }}"
  apiNodeHost: "api-node-{{ .Values.global.host }}"
  pgApiNodeSecretName: "pg-api-node-app"

api:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
      nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
      nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
      nginx.ingress.kubernetes.io/proxy-body-size: 8m
  ~chart: app
  ~needs: [build-api, indice]
  imagePackage: api
  host: "{{ tpl .Values.global.apiHost . }}"
  probesPath: /healthz
  containerPort: 8080
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 4Gi
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: api-sealed-secret
    - configMapRef:
        name: api-configmap
    - configMapRef:
        name: celery-configmap
  env:
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"
    - name: ROOT_URL
      value: "https://{{ tpl .Values.global.apiHost . }}"
    - name: FRONTEND_URL
      value: "https://{{ .Values.global.host }}"

api-node:
  ~chart: app
  ~needs: [build-api-node]
  containerPort: 3000
  imagePackage: api-node
  host: "{{ tpl .Values.global.apiNodeHost . }}"
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgApiNodeSecretName }}"
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 1
      memory: 1Gi

frontend:
  ~chart: app
  ~needs: [build-frontend]
  imagePackage: frontend
  host: "{{ .Values.global.host }}"
  containerPort: 8080
  probesPath: /healthz/
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 1
      memory: 1Gi
  env:
    - name: GATSBY_API_BASE_URL
      value: "https://{{ tpl .Values.global.apiHost . }}" # TODO for some reason, without tpl the value inside apiHost is not evaluated
    - name: GATSBY_API_NODE_BASE_URL
      value: "https://{{ tpl .Values.global.apiNodeHost . }}" # TODO for some reason, without tpl the value inside apiHost is not evaluated
    - name: GATSBY_URL
      value: "https://{{ .Values.global.host }}"
    - name: GATSBY_REPOSITORY_URL
      value: https://github.com/socialgouv/recosante

indice:
  ~chart: app
  ~needs: [build-indice, redis]
  imagePackage: indice
  probesPath: /
  containerPort: 8080
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 4Gi
  startupProbe:
    initialDelaySeconds: 30
    failureThreshold: 500 # for very long migrations
    periodSeconds: 10
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: indice-sealed-secret
    - configMapRef:
        name: celery-configmap
  env:
    - name: SQLALCHEMY_DATABASE_URI
      value: "$(DATABASE_URL)"
    - name: FS_BUCKET_URL
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: REMOTE_SERVER
    - name: FS_BUCKET_USERNAME
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: USERNAME
    - name: FS_BUCKET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ftp-clever-sealed-secret
          key: PASSWORD

redis:
  ~chart: redis
  enabled: true
  ingress:
    enabled: false
  ~forceRestart: false

flower:
  ~needs: [redis]
  ~chart: app
  image: mher/flower:1.2
  containerPort: 5555
  probesPath: /healthcheck
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  ingress:
    enabled: true
  envFrom:
    - secretRef:
        name: flower-sealed-secret
    - configMapRef:
        name: celery-configmap
  env:
    - name: FLOWER_PORT # mandatory, see https://github.com/mher/flower/issues/738
      value: "5555"
    - name: FLOWER_PERSISTENT
      value: "True"


pg-api-node:
  ~chart: pg

cronjobs:
  ~chart: daemon
  ~needs: [build-api-node, pg-api-node]
  imagePackage: app
  replicas: 1
  entrypoint: ["tsx", "./src/cronjobs/index.ts"]
  envFrom:
    - secretRef:
        name: "pg-api-node-app"
    - secretRef:
        name: api-node


jobs:
  runs:
    build-api:
      use: build
      with:
        imagePackage: api
        dockerfile: api/Dockerfile
    build-api-node:
      use: build
      with:
        imagePackage: api-node
        context: api-node
    build-indice:
      use: build
      with:
        imagePackage: indice
        context: libs/indice_pollution
    build-frontend:
      use: build
      ~needs: [api] # yes, the frontend build needs some running API
      with:
        imagePackage: frontend
        dockerfile: frontend/Dockerfile
        buildArgs:
          GATSBY_API_BASE_URL: "https://{{ tpl .Values.global.apiHost . }}" # TODO for some reason, without tpl the value inside apiHost is not evaluated
          GATSBY_API_NODE_BASE_URL: "https://{{ tpl .Values.global.apiNodeHost . }}" # TODO for some reason, without tpl the value inside apiHost is not evaluated
          GATSBY_URL: "https://{{ .Values.global.host }}"
          GATSBY_REPOSITORY_URL: https://github.com/socialgouv/recosante
