"""init

Revision ID: 50ec124dbbfc
Revises: 
Create Date: 2020-09-14 15:44:08.815972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50ec124dbbfc'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ville_entree', sa.String(), nullable=True),
    sa.Column('ville_name', sa.String(), nullable=True),
    sa.Column('ville_insee', sa.String(), nullable=True),
    sa.Column('deplacement', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sport', sa.Boolean(), nullable=True),
    sa.Column('apa', sa.Boolean(), nullable=True),
    sa.Column('activites', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pathologie_respiratoire', sa.Boolean(), nullable=True),
    sa.Column('allergie_pollen', sa.Boolean(), nullable=True),
    sa.Column('fumeur', sa.Boolean(), nullable=True),
    sa.Column('enfants', sa.Boolean(), nullable=True),
    sa.Column('diffusion', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('frequence', sa.String(), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscription')
    # ### end Alembic commands ###
