"""Ajout recommandation_qa et recommandation_raep à Newsletter

Revision ID: 56a71fa504ec
Revises: 5e16e244dcb9
Create Date: 2021-10-13 16:14:24.890642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a71fa504ec'
down_revision = '5e16e244dcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('recommandation_qa_id', sa.Integer(), nullable=True))
    op.add_column('newsletter', sa.Column('recommandation_raep_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_newsletter_webpush_subscription_info_id'), 'newsletter', ['webpush_subscription_info_id'], unique=False)
    op.drop_index('ix_newsletter_webpush_subcription_info_id', table_name='newsletter')
    op.create_foreign_key('fk_newsletter_recommandation_qa', 'newsletter', 'recommandation', ['recommandation_qa_id'], ['id'])
    op.create_foreign_key('fk_newsletter_recommandation_raep', 'newsletter', 'recommandation', ['recommandation_raep_id'], ['id'])


def downgrade():
    op.drop_constraint('fk_newsletter_recommandation_qa', 'newsletter', type_='foreignkey')
    op.drop_constraint('fk_newsletter_recommandation_raep', 'newsletter', type_='foreignkey')
    op.create_index('ix_newsletter_webpush_subcription_info_id', 'newsletter', ['webpush_subscription_info_id'], unique=False)
    op.drop_index(op.f('ix_newsletter_webpush_subscription_info_id'), table_name='newsletter')
    op.drop_column('newsletter', 'recommandation_raep_id')
    op.drop_column('newsletter', 'recommandation_qa_id')