"""Ajout communes pollinarium

Revision ID: 6693ab247cb9
Revises: fd74ffb53677
Create Date: 2021-08-17 15:28:57.801604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '6693ab247cb9'
down_revision = 'fd74ffb53677'
branch_labels = None
depends_on = None


def upgrade():
    for pollinarium in [saint_nazaire, angers, la_roche_sur_yon, cholet, laval, limoges, la_rochelle, lanmary_antonne, saint_feyre, quimper, vannes, rennes, le_havre]:
        op.get_bind().execute(text("""
        UPDATE indice_schema.commune
        SET pollinarium_sentinelle = TRUE
        FROM indice_schema.departement
        WHERE indice_schema.commune.nom = ANY(:communes)
        AND indice_schema.departement.code = ANY(:departements)
        """).bindparams(**pollinarium))


def downgrade():
    pass

saint_nazaire ={
    "departements": ['44', '56', '85'],
    "communes": [
        "Arzal",
        "Assérac",
        "Barbâtre",
        "Batz-sur-Mer",
        "Béganne",
        "Besné",
        "Bouée",
        "Bouin",
        "Caden",
        "Camoël",
        "Campbon",
        "Chaumes-en-Retz",
        "Chauvé",
        "Cordemais",
        "Corsept",
        "Crossac",
        "Donges",
        "Drefféac",
        "Fégréac",
        "Férel",
        "Frossay",
        "Guenrouet",
        "Guérande",
        "Herbignac",
        "La Baule-Escoublac",
        "La Bernerie-en-Retz",
        "La Chapelle-des-Marais",
        "La Chapelle-Launay",
        "La Guérinière",
        "La Plaine-sur-Mer",
        "La Roche-Bernard",
        "La Turballe",
        "Lavau-sur-Loire",
        "Le Croisic",
        "Le Pouliguen",
        "L'Épine",
        "Les Moutiers-en-Retz",
        "Marzan",
        "Mesquer",
        "Missillac",
        "Montoir-de-Bretagne",
        "Nivillac",
        "Noirmoutier-en-l'Île",
        "Paimbœuf",
        "Piriac-sur-Mer",
        "Plessé",
        "Pontchâteau",
        "Pornic",
        "Pornichet",
        "Préfailles",
        "Prinquiau",
        "Quilly",
        "Rieux",
        "Saint-André-des-Eaux",
        "Saint-Brevin-les-Pins",
        "Saint-Dolay",
        "Sainte-Anne-sur-Brivet",
        "Sainte-Reine-de-Bretagne",
        "Saint-Gildas-des-Bois",
        "Saint-Joachim",
        "Saint-Lyphard",
        "Saint-Malo-de-Guersac",
        "Saint-Michel-Chef-Chef",
        "Saint-Molf",
        "Saint-Nazaire",
        "Saint-Père-en-Retz",
        "Saint-Viaud",
        "Savenay",
        "Sévérac",
        "Théhillac",
        "Trignac",
    ]
}

angers = {
    "departements": ['85', '72', '44', '49', '53'],
    "communes": [
        "Angers",
        "Angrie",
        "Aubigné-sur-Layon",
        "Avrillé",
        "Baracé",
        "Baugé-en-Anjou",
        "Bazouges Cré sur Loir",
        "Beaucouzé",
        "Beaufort-en-Anjou",
        "Beaulieu-sur-Layon",
        "Bécon-les-Granits",
        "Béhuard",
        "Bellevigne-en-Layon",
        "Bierné-les-Villages",
        "Blaison-Saint-Sulpice",
        "Bouchemaine",
        "Briollay",
        "Brissac Loire Aubance",
        "Candé",
        "Cantenay-Épinard",
        "Chalonnes-sur-Loire",
        "Chambellay",
        "Champtocé-sur-Loire",
        "Chaudefonds-sur-Layon",
        "Chazé-sur-Argos",
        "Cheffes",
        "Chenillé-Champteussé",
        "Cornillé-les-Caves",
        "Corzé",
        "Daon",
        "Denée",
        "Dénezé-sous-Doué",
        "Doué-en-Anjou",
        "Durtal",
        "Écouflant",
        "Écuillé",
        "Erdre-en-Anjou",
        "Étriché",
        "Feneu",
        "Gennes-Val-de-Loire",
        "Grez-Neuville",
        "Huillé-Lézigné",
        "Ingrandes-Le Fresne sur Loire",
        "Jarzé Villages",
        "Juvardeil",
        "La Chapelle-d'Aligné",
        "La Chapelle-Saint-Laud",
        "La Jaille-Yvon",
        "La Lande-Chasles",
        "La Ménitré",
        "La Possonnière",
        "Le Lion-d'Angers",
        "Le Plessis-Grammoire",
        "Les Bois d'Anjou",
        "Les Garennes sur Loire",
        "Les Hauts-d'Anjou",
        "Les Ponts-de-Cé",
        "Les Rairies",
        "Les Ulmes",
        "Loiré",
        "Loire-Authion",
        "Loireauxence",
        "Longué-Jumelles",
        "Longuenée-en-Anjou",
        "Louresse-Rochemenier",
        "Marcé",
        "Mazé-Milon",
        "Ménil",
        "Miré",
        "Montigné-lès-Rairies",
        "Montrelais",
        "Montreuil-Juigné",
        "Montreuil-sur-Loir",
        "Montreuil-sur-Maine",
        "Morannes sur Sarthe-Daumeray",
        "Mozé-sur-Louet",
        "Mûrs-Erigné",
        "Notre-Dame-du-Pé",
        "Pincé",
        "Précigné",
        "Rives-du-Loir-en-Anjou",
        "Rochefort-sur-Loire",
        "Rou-Marson",
        "Saint-Augustin-des-Bois",
        "Saint-Barthélemy-d'Anjou",
        "Saint-Clément-de-la-Place",
        "Saint-Clément-des-Levées",
        "Saint-Denis-d'Anjou",
        "Sainte-Gemmes-sur-Loire",
        "Saint-Georges-sur-Loire",
        "Saint-Germain-des-Prés",
        "Saint-Jean-de-la-Croix",
        "Saint-Lambert-la-Potherie",
        "Saint-Léger-de-Linières",
        "Saint-Martin-du-Fouilloux",
        "Saint-Melaine-sur-Aubance",
        "Saint-Philbert-du-Peuple",
        "Saint-Sigismond",
        "Sarrigné",
        "Savennières",
        "Sceaux-d'Anjou",
        "Segré-en-Anjou Bleu",
        "Seiches-sur-le-Loir",
        "Sermaise",
        "Soulaines-sur-Aubance",
        "Soulaire-et-Bourg",
        "Terranjou",
        "Thorigné-d'Anjou",
        "Tiercé",
        "Trélazé",
        "Tuffalun",
        "Val d'Erdre-Auxence",
        "Val-du-Layon",
        "Verrie",
        "Verrières-en-Anjou",
    ]
}

la_roche_sur_yon = {
    "departements": ['85', '17', '44'],
    "communes": [
        "Bournezeau",
        "Brem-sur-Mer",
        "Bretignolles-sur-Mer",
        "Challans",
        "Chantonnay",
        "Chasnais",
        "Château-Guibert",
        "Chauché",
        "Chavagnes-en-Paillers",
        "Coëx",
        "Commequiers",
        "Corpe",
        "Curzon",
        "Dompierre-sur-Yon",
        "Essarts en Bocage",
        "Falleron",
        "Fougeré",
        "Froidfond",
        "Givrand",
        "Grand'Landes",
        "Grosbreuil",
        "Jard-sur-Mer",
        "La Boissière-des-Landes",
        "La Bretonnière-la-Claye",
        "La Caillère-Saint-Hilaire",
        "La Chaize-Giraud",
        "La Chaize-le-Vicomte",
        "La Chapelle-Hermier",
        "La Chapelle-Palluau",
        "La Chapelle-Thémer",
        "La Copechagnière",
        "La Couture",
        "La Ferrière",
        "La Garnache",
        "La Genétouze",
        "La Jaudonnière",
        "La Jonchère",
        "La Merlatière",
        "La Rabatelière",
        "La Réorthe",
        "La Roche-sur-Yon",
        "L'Aiguillon-sur-Vie",
        "Lairoux",
        "Landeronde",
        "Landevieille",
        "Le Bernard",
        "Le Champ-Saint-Père",
        "Le Fenouiller",
        "Le Girouard",
        "Le Givre",
        "Le Poiré-sur-Vie",
        "Le Tablier",
        "Legé",
        "Les Achards",
        "Les Brouzils",
        "Les Lucs-sur-Boulogne",
        "Les Magnils-Reigniers",
        "Les Pineaux",
        "Les Sables-d'Olonne",
        "L'Herbergement",
        "L'Île-d'Olonne",
        "Longeville-sur-Mer",
        "Luçon",
        "Maché",
        "Mareuil-sur-Lay-Dissais",
        "Martinet",
        "Montréverd",
        "Mouchamps",
        "Mouilleron-le-Captif",
        "Moutiers-les-Mauxfaits",
        "Moutiers-sur-le-Lay",
        "Nesmy",
        "Nieul-le-Dolent",
        "Notre-Dame-de-Riez",
        "Palluau",
        "Péault",
        "Poiroux",
        "Rives de l'Yon",
        "Rocheservière",
        "Rosnay",
        "Saint-André-Goule-d'Oie",
        "Saint-Aubin-la-Plaine",
        "Saint-Avaugourd-des-Landes",
        "Saint-Benoist-sur-Mer",
        "Saint-Christophe-du-Ligneron",
        "Saint-Cyr-en-Talmondais",
        "Saint-Denis-la-Chevasse",
        "Sainte-Cécile",
        "Sainte-Flaive-des-Loups",
        "Sainte-Foy",
        "Sainte-Gemme-la-Plaine",
        "Sainte-Hermine",
        "Sainte-Pexine",
        "Saint-Étienne-de-Brillouet",
        "Saint-Étienne-du-Bois",
        "Saint-Fulgent",
        "Saint-Georges-de-Pointindoux",
        "Saint-Germain-de-Prinçay",
        "Saint-Gilles-Croix-de-Vie",
        "Saint-Hilaire-de-Riez",
        "Saint-Hilaire-la-Forêt",
        "Saint-Hilaire-le-Vouhis",
        "Saint-Jean-de-Beugné",
        "Saint-Juire-Champgillon",
        "Saint-Julien-des-Landes",
        "Saint-Maixent-sur-Vie",
        "Saint-Martin-des-Noyers",
        "Saint-Martin-Lars-en-Sainte-Hermine",
        "Saint-Mathurin",
        "Saint-Paul-Mont-Penit",
        "Saint-Révérend",
        "Saint-Vincent-Sterlanges",
        "Saint-Vincent-sur-Graon",
        "Saint-Vincent-sur-Jard",
        "Sigournais",
        "Soullans",
        "Talmont-Saint-Hilaire",
        "Thiré",
        "Thorigny",
        "Touvois",
        "Vairé",
        "Venansault",
        "Vendrennes",
    ]
}

cholet = {
    "departements": ['79', '85', '37', '49', '17', '44'],
    "communes":[
        "Argentonnay",
        "Bazoges-en-Paillers",
        "Beaupréau-en-Mauges",
        "Beaurepaire",
        "Bégrolles-en-Mauges",
        "Boussay",
        "Bressuire",
        "Bretignolles",
        "Cerizay",
        "Cernusson",
        "Chanteloup-les-Bois",
        "Chanverrie",
        "Chavagnes-les-Redoux",
        "Chemillé-en-Anjou",
        "Cholet",
        "Cirières",
        "Cléré-sur-Layon",
        "Combrand",
        "Coron",
        "Courlay",
        "Cugand",
        "Genneton",
        "Gétigné",
        "La Boissière-de-Montaigu",
        "La Bruffière",
        "La Forêt-sur-Sèvre",
        "La Gaubretière",
        "La Meilleraie-Tillay",
        "La Petite-Boissière",
        "La Plaine",
        "La Regrippière",
        "La Romagne",
        "La Séguinière",
        "La Tessoualle",
        "Le Boupère",
        "Le May-sur-Èvre",
        "Le Pin",
        "Les Cerqueux",
        "Les Epesses",
        "Les Herbiers",
        "Les Landes-Genusson",
        "Lys-Haut-Layon",
        "Mallièvre",
        "Mauges-sur-Loire",
        "Mauléon",
        "Maulévrier",
        "Mazières-en-Mauges",
        "Menomblet",
        "Mesnard-la-Barotière",
        "Monsireigne",
        "Montaigu-Vendée",
        "Montilliers",
        "Montournais",
        "Montravers",
        "Montrevault-sur-Èvre",
        "Mortagne-sur-Sèvre",
        "Nuaillé",
        "Nueil-les-Aubiers",
        "Passavant-sur-Layon",
        "Pouzauges",
        "Réaumur",
        "Rochetrejoux",
        "Saint Maurice Étusson",
        "Saint-Amand-sur-Sèvre",
        "Saint-André-sur-Sèvre",
        "Saint-Aubin-des-Ormeaux",
        "Saint-Aubin-du-Plain",
        "Saint-Christophe-du-Bois",
        "Saint-Laurent-sur-Sèvre",
        "Saint-Léger-sous-Cholet",
        "Saint-Malô-du-Bois",
        "Saint-Mars-la-Réorthe",
        "Saint-Martin-des-Tilleuls",
        "Saint-Mesmin",
        "Saint-Paul-du-Bois",
        "Saint-Paul-en-Pareds",
        "Saint-Pierre-des-Échaubrognes",
        "Saint-Prouant",
        "Sèvremoine",
        "Sèvremont",
        "Sigournais",
        "Somloire",
        "Terranjou",
        "Tiffauges",
        "Toutlemonde",
        "Treize-Septiers",
        "Treize-Vents",
        "Trémentines",
        "Val en Vignes",
        "Vezins",
        "Voulmentin",
        "Yzernay",
    ]
}

laval = {
    "departements": ['14', '35', '53', '49', '72'],
    "communes": [
        "Ahuillé",
        "Alexain",
        "Ambrières-les-Vallées",
        "Andouillé",
        "Argentré",
        "Argentré-du-Plessis",
        "Aron",
        "Arquenay",
        "Assé-le-Bérenger",
        "Astillé",
        "Athée",
        "Auvers-le-Hamon",
        "Availles-sur-Seiche",
        "Bais",
        "Bais",
        "Balazé",
        "Ballots",
        "Bannes",
        "Bazougers",
        "Beaulieu-sur-Oudon",
        "Beaumont-Pied-de-Bœuf",
        "Belgeard",
        "Blandouet-Saint Jean",
        "Bonchamp-lès-Laval",
        "Bouchamps-lès-Craon",
        "Bouère",
        "Bouessay",
        "Bouillé-Ménard",
        "Bourgon",
        "Brains-sur-les-Marches",
        "Bréal-sous-Vitré",
        "Brecé",
        "Brée",
        "Brielles",
        "Carelles",
        "Chailland",
        "Châlons-du-Maine",
        "Champéon",
        "Champgenéteux",
        "Changé",
        "Château-Gontier-sur-Mayenne",
        "Châtelain",
        "Châtillon-en-Vendelais",
        "Châtillon-sur-Colmont",
        "Chemazé",
        "Chémeré-le-Roi",
        "Chérancé",
        "Colombiers-du-Plessis",
        "Commer",
        "Congrier",
        "Contest",
        "Cosmes",
        "Cossé-en-Champagne",
        "Cossé-le-Vivien",
        "Coudray",
        "Courbeveille",
        "Craon",
        "Cuillé",
        "Denazé",
        "Entrammes",
        "Erbrée",
        "Ernée",
        "Étrelles",
        "Évron",
        "Fleurigné",
        "Fontaine-Couverte",
        "Forcé",
        "Fromentières",
        "Gastines",
        "Gennes-Longuefuye",
        "Gennes-sur-Seiche",
        "Gesnes",
        "Gorron",
        "Grazay",
        "Grez-en-Bouère",
        "Hambers",
        "Hardanges",
        "Hercé",
        "Houssay",
        "Izé",
        "Jublains",
        "Juvigné",
        "La Baconnière",
        "La Bazoge-Montpinçon",
        "La Bazouge-de-Chemeré",
        "La Bazouge-des-Alleux",
        "La Bigottière",
        "La Boissière",
        "La Brûlatte",
        "La Chapelle-Anthenaise",
        "La Chapelle-au-Riboul",
        "La Chapelle-Craonnaise",
        "La Chapelle-Erbrée",
        "La Chapelle-Janson",
        "La Chapelle-Rainsouin",
        "La Croixille",
        "La Cropte",
        "La Gravelle",
        "La Guerche-de-Bretagne",
        "La Haie-Traversaine",
        "La Pellerine",
        "La Roche-Neuville",
        "La Roë",
        "La Selle-Craonnaise",
        "La Selle-en-Luitré",
        "La Selle-Guerchaise",
        "Larchamp",
        "Laubrières",
        "Launay-Villiers",
        "Laval",
        "Le Bignon-du-Maine",
        "Le Bourgneuf-la-Forêt",
        "Le Buret",
        "Le Genest-Saint-Isle",
        "Le Pas",
        "Le Pertre",
        "Levaré",
        "L'Huisserie",
        "Livet",
        "Livré-la-Touche",
        "Loiron-Ruillé",
        "Louverné",
        "Louvigné",
        "Luitré-Dompierre",
        "Maisoncelles-du-Maine",
        "Marcillé-la-Ville",
        "Marigné-Peuton",
        "Martigné-sur-Mayenne",
        "Mayenne",
        "Mée",
        "Ménil",
        "Méral",
        "Meslay-du-Maine",
        "Mézangers",
        "Mondevert",
        "Montaudin",
        "Montautour",
        "Montenay",
        "Montflours",
        "Montigné-le-Brillant",
        "Montjean",
        "Montreuil-Poulay",
        "Montsûrs",
        "Moulay",
        "Moutiers",
        "Neau",
        "Niafles",
        "Nuillé-sur-Vicoin",
        "Oisseau",
        "Olivet",
        "Origné",
        "Parcé",
        "Parigné-sur-Braye",
        "Parné-sur-Roc",
        "Peuton",
        "Placé",
        "Pocé-les-Bois",
        "Pommerieux",
        "Port-Brillet",
        "Préaux",
        "Prée-d'Anjou",
        "Princé",
        "Quelaines-Saint-Gault",
        "Rannée",
        "Renazé",
        "Ruillé-Froid-Fonds",
        "Sacé",
        "Saint-Aignan-sur-Roë",
        "Saint-Aubin-des-Landes",
        "Saint-Baudelle",
        "Saint-Berthevin",
        "Saint-Berthevin-la-Tannière",
        "Saint-Brice",
        "Saint-Charles-la-Forêt",
        "Saint-Christophe-des-Bois",
        "Saint-Cyr-le-Gravelais",
        "Saint-Denis-de-Gastines",
        "Saint-Denis-d'Orques",
        "Saint-Denis-du-Maine",
        "Sainte-Gemmes-le-Robert",
        "Sainte-Suzanne-et-Chammes",
        "Saint-Fraimbault-de-Prières",
        "Saint-Georges-Buttavent",
        "Saint-Georges-le-Fléchard",
        "Saint-Georges-sur-Erve",
        "Saint-Germain-d'Anxure",
        "Saint-Germain-du-Pinel",
        "Saint-Germain-le-Fouilloux",
        "Saint-Germain-le-Guillaume",
        "Saint-Hilaire-du-Maine",
        "Saint-Jean-sur-Mayenne",
        "Saint-Léger",
        "Saint-Loup-du-Dorat",
        "Saint-Loup-du-Gast",
        "Saint-Mars-sur-Colmont",
        "Saint-Martin-du-Limet",
        "Saint-M'Hervé",
        "Saint-Michel-de-la-Roë",
        "Saint-Ouën-des-Toits",
        "Saint-Pierre-des-Landes",
        "Saint-Pierre-la-Cour",
        "Saint-Pierre-sur-Erve",
        "Saint-Poix",
        "Saint-Quentin-les-Anges",
        "Saint-Saturnin-du-Limet",
        "Saulges",
        "Simplé",
        "Soulgé-sur-Ouette",
        "Souvigné-sur-Sarthe",
        "Taillis",
        "Thorigné-en-Charnie",
        "Torcé",
        "Torcé-Viviers-en-Charnie",
        "Vaiges",
        "Val-du-Maine",
        "Vautorte",
        "Vergéal",
        "Villiers-Charlemagne",
        "Viré-en-Champagne",
        "Vitré",
        "Voutré",
    ]
}

limoges = {
    "departements": ['16', '87', '19', '24', '86', '23', '17'],
    "communes": [
        "Aixe-sur-Vienne",
        "Ambazac",
        "Augne",
        "Aureil",
        "Auriat",
        "Balledent",
        "Bellac",
        "Benayes",
        "Berneuil",
        "Bersac-sur-Rivalier",
        "Bessines-sur-Gartempe",
        "Beynac",
        "Blanzac",
        "Blond",
        "Boisseuil",
        "Bonnac-la-Côte",
        "Bosmie-l'Aiguille",
        "Breuilaufa",
        "Brigueuil",
        "Bujaleuf",
        "Burgnac",
        "Bussière-Galant",
        "Chaillac-sur-Vienne",
        "Châlus",
        "Chamboret",
        "Champagnac-la-Rivière",
        "Champnétery",
        "Champsac",
        "Chaptelat",
        "Chassenon",
        "Château-Chervix",
        "Châteauneuf-la-Forêt",
        "Châteauponsac",
        "Cheissoux",
        "Chéronnac",
        "Cieux",
        "Cognac-la-Forêt",
        "Compreignac",
        "Condat-sur-Vienne",
        "Coussac-Bonneval",
        "Couzeix",
        "Cussac",
        "Domps",
        "Dournazac",
        "Droux",
        "Étagnac",
        "Eybouleuf",
        "Eyjeaux",
        "Eymoutiers",
        "Feytiat",
        "Firbeix",
        "Flavignac",
        "Folles",
        "Fromental",
        "Glandon",
        "Glanges",
        "Gorre",
        "Isle",
        "Jabreilles-les-Bordes",
        "Janailhac",
        "Javerdat",
        "Jourgnac",
        "La Chapelle-Montbrandeix",
        "La Croisille-sur-Briance",
        "La Geneytouse",
        "La Jonchère-Saint-Maurice",
        "La Meyze",
        "La Porcherie",
        "La Roche-l'Abeille",
        "Ladignac-le-Long",
        "Laurière",
        "Lavignac",
        "Le Buis",
        "Le Chalard",
        "Le Châtenet-en-Dognon",
        "Le Palais-sur-Vienne",
        "Le Vigen",
        "Les Billanges",
        "Les Cars",
        "Limoges",
        "Linards",
        "Magnac-Bourg",
        "Marsac",
        "Masléon",
        "Masseret",
        "Meilhac",
        "Meuzac",
        "Moissannes",
        "Montgibaud",
        "Montrollet",
        "Montrol-Sénard",
        "Mortemart",
        "Nantiat",
        "Neuvic-Entier",
        "Nexon",
        "Nieul",
        "Nouic",
        "Oradour-sur-Glane",
        "Oradour-sur-Vayres",
        "Pageas",
        "Panazol",
        "Peyrat-de-Bellac",
        "Peyrilhac",
        "Pierre-Buffière",
        "Pressignac",
        "Rancon",
        "Razès",
        "Rilhac-Lastours",
        "Rilhac-Rancon",
        "Rochechouart",
        "Royères",
        "Roziers-Saint-Georges",
        "Saillat-sur-Vienne",
        "Saint-Amand-Jartoudeix",
        "Saint-Amand-le-Petit",
        "Saint-Amand-Magnazeix",
        "Saint-Auvent",
        "Saint-Bazile",
        "Saint-Bonnet-Briance",
        "Saint-Brice-sur-Vienne",
        "Saint-Christophe",
        "Saint-Cyr",
        "Saint-Denis-des-Murs",
        "Sainte-Anne-Saint-Priest",
        "Sainte-Marie-de-Vaux",
        "Saint-Gence",
        "Saint-Genest-sur-Roselle",
        "Saint-Germain-les-Belles",
        "Saint-Gilles-les-Forêts",
        "Saint-Hilaire-Bonneval",
        "Saint-Hilaire-les-Places",
        "Saint-Jean-Ligoure",
        "Saint-Jouvent",
        "Saint-Julien-le-Petit",
        "Saint-Junien",
        "Saint-Junien-les-Combes",
        "Saint-Just-le-Martel",
        "Saint-Laurent-les-Églises",
        "Saint-Laurent-sur-Gorre",
        "Saint-Léger-la-Montagne",
        "Saint-Léonard-de-Noblat",
        "Saint-Martin-de-Jussac",
        "Saint-Martin-le-Vieux",
        "Saint-Martin-Sainte-Catherine",
        "Saint-Martin-Terressus",
        "Saint-Maurice-les-Brousses",
        "Saint-Méard",
        "Saint-Moreil",
        "Saint-Ouen-sur-Gartempe",
        "Saint-Pardoux-le-Lac",
        "Saint-Paul",
        "Saint-Pierre-de-Frugie",
        "Saint-Priest-Ligoure",
        "Saint-Priest-Palus",
        "Saint-Priest-sous-Aixe",
        "Saint-Priest-Taurion",
        "Saint-Sulpice-Laurière",
        "Saint-Sylvestre",
        "Saint-Victurnien",
        "Saint-Vitte-sur-Briance",
        "Saint-Yrieix-la-Perche",
        "Saint-Yrieix-sous-Aixe",
        "Saulgond",
        "Sauviat-sur-Vige",
        "Séreilhac",
        "Solignac",
        "Surdoux",
        "Sussac",
        "Thouron",
        "Vaulry",
        "Vayres",
        "Verneuil-sur-Vienne",
        "Veyrac",
        "Vicq-sur-Breuilh",
        "Villefavard",
    ]
}

la_rochelle = {
    "departements": ['17', '85', '79', '16', '23'],
    "communes": [
        "Aigrefeuille-d'Aunis",
        "Anais",
        "Andilly",
        "Angliers",
        "Angoulins",
        "Annezay",
        "Arçais",
        "Ardillières",
        "Ars-en-Ré",
        "Auchay-sur-Vendée",
        "Aytré",
        "Ballon",
        "Beaugeay",
        "Benon",
        "Bouhet",
        "Bourcefranc-le-Chapus",
        "Bourgneuf",
        "Breuil-la-Réorte",
        "Breuil-Magné",
        "Cabariot",
        "Chaillé-les-Marais",
        "Chambon",
        "Champagné-les-Marais",
        "Champdolent",
        "Charron",
        "Châtelaillon-Plage",
        "Ciré-d'Aunis",
        "Clavette",
        "Courçon",
        "Cramchaban",
        "Croix-Chapeau",
        "Damvix",
        "Doix lès Fontaines",
        "Dolus-d'Oléron",
        "Dompierre-sur-Mer",
        "Échillais",
        "Esnandes",
        "Ferrières",
        "Forges",
        "Fouras",
        "Genouillé",
        "Grues",
        "Île-d'Aix",
        "La Brée-les-Bains",
        "La Couarde-sur-Mer",
        "La Devise",
        "La Faute-sur-Mer",
        "La Flotte",
        "La Grève-sur-Mignon",
        "La Jarne",
        "La Jarrie",
        "La Laigne",
        "La Rochelle",
        "La Ronde",
        "La Taillée",
        "La Tranche-sur-Mer",
        "La Vallée",
        "Lagord",
        "L'Aiguillon-sur-Mer",
        "Landrais",
        "Le Bois-Plage-en-Ré",
        "Le Château-d'Oléron",
        "Le Grand-Village-Plage",
        "Le Gué-d'Alleré",
        "Le Gué-de-Velluire",
        "Le Langon",
        "Le Thou",
        "Les Portes-en-Ré",
        "Les Velluire-sur-Vendée",
        "L'Houmeau",
        "L'Île-d'Elle",
        "Loire-les-Marais",
        "Loix",
        "Longèves",
        "Lussant",
        "Maillé",
        "Marans",
        "Marennes-Hiers-Brouage",
        "Marsilly",
        "Mauzé-sur-le-Mignon",
        "Moëze",
        "Montreuil",
        "Montroy",
        "Moragne",
        "Moreilles",
        "Mouzeuil-Saint-Martin",
        "Muron",
        "Nalliers",
        "Nieul-sur-Mer",
        "Nuaillé-d'Aunis",
        "Périgny",
        "Port-des-Barques",
        "Puilboreau",
        "Puy-du-Lac",
        "Puyravault",
        "Puyravault",
        "Rivedoux-Plage",
        "Rochefort",
        "Saint-Agnant",
        "Saint-Christophe",
        "Saint-Clément-des-Baleines",
        "Saint-Coutant-le-Grand",
        "Saint-Crépin",
        "Saint-Cyr-du-Doret",
        "Saint-Denis-d'Oléron",
        "Saint-Denis-du-Payré",
        "Sainte-Marie-de-Ré",
        "Sainte-Radégonde-des-Noyers",
        "Sainte-Soulle",
        "Saint-Froult",
        "Saint-Georges-d'Oléron",
        "Saint-Georges-du-Bois",
        "Saint-Hilaire-la-Palud",
        "Saint-Hippolyte",
        "Saint-Jean-de-Liversay",
        "Saint-Laurent-de-la-Prée",
        "Saint-Mard",
        "Saint-Martin-de-Ré",
        "Saint-Médard-d'Aunis",
        "Saint-Michel-en-l'Herm",
        "Saint-Nazaire-sur-Charente",
        "Saint-Ouen-d'Aunis",
        "Saint-Pierre-d'Amilly",
        "Saint-Pierre-d'Oléron",
        "Saint-Pierre-La-Noue",
        "Saint-Rogatien",
        "Saint-Saturnin-du-Bois",
        "Saint-Sauveur-d'Aunis",
        "Saint-Trojan-les-Bains",
        "Saint-Vivien",
        "Saint-Xandre",
        "Salles-sur-Mer",
        "Soubise",
        "Surgères",
        "Taugon",
        "Thairé",
        "Tonnay-Charente",
        "Triaize",
        "Trizay",
        "Vergeroux",
        "Vérines",
        "Villedoux",
        "Virson",
        "Vix",
        "Vouhé",
        "Vouillé-les-Marais",
        "Yves",
    ]
}

lanmary_antonne = {
    "departements": ['24', '16', '33', '17', '87', '19', '46', '82', '47'],
    "communes": [
        "Agonac",
        "Ajat",
        "Alles-sur-Dordogne",
        "Angoisse",
        "Anlhiac",
        "Annesse-et-Beaulieu",
        "Antonne-et-Trigonant",
        "Aubas",
        "Audrix",
        "Auriac-du-Périgord",
        "Ayen",
        "Azerat",
        "Badefols-d'Ans",
        "Bars",
        "Bassillac et Auberoche",
        "Beauregard-de-Terrasson",
        "Beauregard-et-Bassac",
        "Beauronne",
        "Beleymas",
        "Bertric-Burée",
        "Biras",
        "Boisseuilh",
        "Boulazac Isle Manoire",
        "Bourdeilles",
        "Bourg-des-Maisons",
        "Bourrou",
        "Brantôme en Périgord",
        "Brouchaud",
        "Bussac",
        "Calès",
        "Campagne",
        "Campsegret",
        "Celles",
        "Chalagnac",
        "Chalais",
        "Champagnac-de-Belair",
        "Champcevinel",
        "Champs-Romain",
        "Chancelade",
        "Chantérac",
        "Chapdeuil",
        "Château-l'Évêque",
        "Châtres",
        "Cherveix-Cubas",
        "Chourgnac",
        "Clermont-de-Beauregard",
        "Clermont-d'Excideuil",
        "Coly-Saint-Amand",
        "Condat-sur-Trincou",
        "Condat-sur-Vézère",
        "Corgnac-sur-l'Isle",
        "Cornille",
        "Coubjours",
        "Coulaures",
        "Coulounieix-Chamiers",
        "Coursac",
        "Coutures",
        "Creyssac",
        "Creyssensac-et-Pissot",
        "Cubjac-Auvézère-Val d'Ans",
        "Cublac",
        "Douchapt",
        "Douville",
        "Douzillac",
        "Dussac",
        "Église-Neuve-de-Vergt",
        "Escoire",
        "Excideuil",
        "Eyzerac",
        "Fanlac",
        "Fleurac",
        "Fossemagne",
        "Fouleix",
        "Gabillou",
        "Génis",
        "Grand-Brassac",
        "Granges-d'Ans",
        "Grignols",
        "Grun-Bordas",
        "Hautefort",
        "Issac",
        "Jaure",
        "Journiac",
        "Jumilhac-le-Grand",
        "La Bachellerie",
        "La Chapelle-Aubareil",
        "La Chapelle-Faucher",
        "La Chapelle-Gonaguet",
        "La Chapelle-Montabourlet",
        "La Chapelle-Montmoreau",
        "La Chapelle-Saint-Jean",
        "La Coquille",
        "La Douze",
        "La Tour-Blanche-Cercles",
        "Lacropte",
        "Lanouaille",
        "Le Bugue",
        "Le Lardin-Saint-Lazare",
        "Léguillac-de-l'Auche",
        "Lempzours",
        "Les Eyzies",
        "Les Farges",
        "Limeuil",
        "Limeyrat",
        "Liorac-sur-Louyre",
        "Lisle",
        "Louignac",
        "Lussas-et-Nontronneau",
        "Manzac-sur-Vern",
        "Mareuil en Périgord",
        "Marquay",
        "Marsac-sur-l'Isle",
        "Mauzac-et-Grand-Castang",
        "Mauzens-et-Miremont",
        "Mayac",
        "Mensignac",
        "Meyrals",
        "Mialet",
        "Milhac-de-Nontron",
        "Montagnac-d'Auberoche",
        "Montagnac-la-Crempse",
        "Montagrier",
        "Montignac-Lascaux",
        "Montrem",
        "Nailhac",
        "Nantheuil",
        "Nanthiat",
        "Négrondes",
        "Neuvic",
        "Nontron",
        "Paunat",
        "Paussac-et-Saint-Vivien",
        "Payzac",
        "Périgueux",
        "Perpezac-le-Blanc",
        "Peyrignac",
        "Peyzac-le-Moustier",
        "Pezuls",
        "Plazac",
        "Pressignac-Vicq",
        "Preyssac-d'Excideuil",
        "Quinsac",
        "Razac-sur-l'Isle",
        "Ribérac",
        "Rosiers-de-Juillac",
        "Rouffignac-Saint-Cernin-de-Reilhac",
        "Rudeau-Ladosse",
        "Saint-Amand-de-Vergt",
        "Saint-Aquilin",
        "Saint-Astier",
        "Saint-Avit-de-Vialard",
        "Saint-Chamassy",
        "Saint-Crépin-d'Auberoche",
        "Sainte-Eulalie-d'Ans",
        "Sainte-Foy-de-Longas",
        "Sainte-Orse",
        "Sainte-Trie",
        "Saint-Félix-de-Bourdeilles",
        "Saint-Félix-de-Reillac-et-Mortemart",
        "Saint-Félix-de-Villadeix",
        "Saint-Front-d'Alemps",
        "Saint-Front-la-Rivière",
        "Saint-Front-sur-Nizonne",
        "Saint-Georges-de-Montclard",
        "Saint-Germain-des-Prés",
        "Saint-Germain-du-Salembre",
        "Saint-Geyrac",
        "Saint-Hilaire-d'Estissac",
        "Saint-Jean-d'Ataux",
        "Saint-Jean-de-Côle",
        "Saint-Jean-d'Estissac",
        "Saint-Jory-de-Chalais",
        "Saint-Jory-las-Bloux",
        "Saint-Just",
        "Saint-Léon-sur-l'Isle",
        "Saint-Léon-sur-Vézère",
        "Saint-Louis-en-l'Isle",
        "Saint-Marcel-du-Périgord",
        "Saint-Martial-d'Albarède",
        "Saint-Martial-de-Valette",
        "Saint-Martin-de-Fressengeas",
        "Saint-Martin-de-Ribérac",
        "Saint-Martin-des-Combes",
        "Saint-Mayme-de-Péreyrol",
        "Saint-Méard-de-Drône",
        "Saint-Médard-d'Excideuil",
        "Saint-Mesmin",
        "Saint-Michel-de-Villadeix",
        "Saint-Pancrace",
        "Saint-Pantaly-d'Excideuil",
        "Saint-Pardoux-de-Drône",
        "Saint-Pardoux-la-Rivière",
        "Saint-Paul-de-Serre",
        "Saint-Paul-la-Roche",
        "Saint-Pierre-de-Chignac",
        "Saint-Pierre-de-Côle",
        "Saint-Priest-les-Fougères",
        "Saint-Rabier",
        "Saint-Raphaël",
        "Saint-Robert",
        "Saint-Romain-et-Saint-Clément",
        "Saint-Saud-Lacoussière",
        "Saint-Séverin-d'Estissac",
        "Saint-Sulpice-de-Roumagnac",
        "Saint-Sulpice-d'Excideuil",
        "Saint-Victor",
        "Saint-Vincent-de-Connezac",
        "Saint-Vincent-sur-l'Isle",
        "Salagnac",
        "Salon",
        "Sanilhac",
        "Sarlande",
        "Sarliac-sur-l'Isle",
        "Sarrazac",
        "Savignac-de-Miremont",
        "Savignac-de-Nontron",
        "Savignac-Lédrier",
        "Savignac-les-Églises",
        "Sceau-Saint-Angel",
        "Segonzac",
        "Segonzac",
        "Sergeac",
        "Siorac-de-Ribérac",
        "Sorges et Ligueux en Périgord",
        "Sourzac",
        "Tamniès",
        "Teillots",
        "Temple-Laguyon",
        "Terrasson-Lavilledieu",
        "Thenon",
        "Thiviers",
        "Thonac",
        "Tocane-Saint-Apre",
        "Tourtoirac",
        "Trélissac",
        "Trémolat",
        "Tursac",
        "Val de Louyre et Caudeau",
        "Vallereuil",
        "Valojoulx",
        "Vaunac",
        "Vergt",
        "Verteillac",
        "Veyrines-de-Vergt",
        "Villac",
        "Villamblard",
        "Villars",
        "Villetoureix",
    ]
}

saint_feyre = {
    "departements": ['23', '87', '19', '36', '18', '03', '63'],
    "communes": [
        "Dun-le-Palestel",
        "Faux-Mazuras",
        "Felletin",
        "Fleurat",
        "Fransèches",
        "Fresselines",
        "Fursac",
        "Gartempe",
        "Genouillac",
        "Glénic",
        "Gouzon",
        "Guéret",
        "Issoudun-Létrieix",
        "Jalesches",
        "Janaillat",
        "Jarnages",
        "Jouillat",
        "La Brionne",
        "La Celle-Dunoise",
        "La Celle-sous-Gouzon",
        "La Cellette",
        "La Chapelle-Baloue",
        "La Chapelle-Saint-Martial",
        "La Chapelle-Taillefert",
        "La Chaussade",
        "La Forêt-du-Temple",
        "La Nouaille",
        "La Pouge",
        "La Saunière",
        "La Serre-Bussière-Vieille",
        "La Souterraine",
        "Ladapeyre",
        "Lafat",
        "Lavaufranche",
        "Lavaveix-les-Mines",
        "Le Bourg-d'Hem",
        "Le Chauchet",
        "Le Donzeil",
        "Le Grand-Bourg",
        "Le Monteil-au-Vicomte",
        "Lépaud",
        "Lépinas",
        "Leyrat",
        "Linard-Malval",
        "Lizières",
        "Lourdoueix-Saint-Michel",
        "Lourdoueix-Saint-Pierre",
        "Lupersat",
        "Lussat",
        "Mainsat",
        "Maison-Feyne",
        "Maisonnisses",
        "Malleret-Boussac",
        "Mansat-la-Courrière",
        "Marsac",
        "Mazeirat",
        "Méasnes",
        "Montaigut-le-Blanc",
        "Montboucher",
        "Mortroux",
        "Mourioux-Vieilleville",
        "Moutier-d'Ahun",
        "Moutier-Malcard",
        "Moutier-Rozeille",
        "Naillat",
        "Néoux",
        "Noth",
        "Nouzerines",
        "Nouzerolles",
        "Nouziers",
        "Parsac-Rimondeix",
        "Peyrabout",
        "Peyrat-la-Nonière",
        "Peyrat-le-Château",
        "Pierrefitte",
        "Pionnat",
        "Pontarion",
        "Pouligny-Notre-Dame",
        "Puy-Malsignat",
        "Roches",
        "Royère-de-Vassivière",
        "Sagnat",
        "Saint-Agnant-de-Versillat",
        "Saint-Alpinien",
        "Saint-Amand",
        "Saint-Avit-de-Tardes",
        "Saint-Avit-le-Pauvre",
        "Saint-Chabrais",
        "Saint-Dizier-la-Tour",
        "Saint-Dizier-les-Domaines",
        "Saint-Dizier-Masbaraud",
        "Saint-Domet",
        "Sainte-Feyre",
        "Sainte-Feyre-la-Montagne",
        "Saint-Éloi",
        "Saint-Fiel",
        "Saint-Frion",
        "Saint-Georges-la-Pouge",
        "Saint-Germain-Beaupré",
        "Saint-Goussaud",
        "Saint-Hilaire-la-Plaine",
        "Saint-Hilaire-le-Château",
        "Saint-Julien-le-Châtel",
        "Saint-Junien-la-Bregère",
        "Saint-Laurent",
        "Saint-Léger-Bridereix",
        "Saint-Léger-le-Guérétois",
        "Saint-Loup",
        "Saint-Maixant",
        "Saint-Marc-à-Frongier",
        "Saint-Marc-à-Loubaud",
        "Saint-Marien",
        "Saint-Martial-le-Mont",
        "Saint-Martin-Château",
        "Saint-Maurice-la-Souterraine",
        "Saint-Médard-la-Rochette",
        "Saint-Michel-de-Veisse",
        "Saint-Pardoux-le-Neuf",
        "Saint-Pardoux-les-Cards",
        "Saint-Pardoux-Morterolles",
        "Saint-Pierre-Bellevue",
        "Saint-Pierre-Chérignat",
        "Saint-Pierre-le-Bost",
        "Saint-Priest",
        "Saint-Priest-la-Feuille",
        "Saint-Priest-la-Plaine",
        "Saint-Quentin-la-Chabanne",
        "Saint-Silvain-Bas-le-Roc",
        "Saint-Silvain-Bellegarde",
        "Saint-Silvain-Montaigut",
        "Saint-Silvain-sous-Toulx",
        "Saint-Sulpice-le-Dunois",
        "Saint-Sulpice-le-Guérétois",
        "Saint-Sulpice-les-Champs",
        "Saint-Vaury",
        "Saint-Victor-en-Marche",
        "Saint-Yrieix-la-Montagne",
        "Saint-Yrieix-les-Bois",
        "Sannat",
        "Sardent",
        "Savennes",
        "Sazeray",
        "Soubrebost",
        "Soumans",
        "Sous-Parsat",
        "Tardes",
        "Tercillat",
        "Thauron",
        "Toulx-Sainte-Croix",
        "Trois-Fonds",
        "Vallière",
        "Vareilles",
        "Verneiges",
        "Vidaillat",
        "Vigeville",
        "Vigoulant",
        "Vijon",
        "Villard",
    ]
}

quimper = {
    "departements": ['29', '56', '22'],
    "communes": [
        "Argol",
        "Audierne",
        "Bannalec",
        "Bénodet",
        "Beuzec-Cap-Sizun",
        "Brasparts",
        "Briec",
        "Cast",
        "Châteaulin",
        "Châteauneuf-du-Faou",
        "Clohars-Fouesnant",
        "Combrit",
        "Concarneau",
        "Confort-Meilars",
        "Coray",
        "Dinéault",
        "Douarnenez",
        "Edern",
        "Elliant",
        "Ergué-Gabéric",
        "Fouesnant",
        "Gouesnach",
        "Gouézec",
        "Goulien",
        "Gourlizon",
        "Guengat",
        "Guiler-sur-Goyen",
        "Guilvinec",
        "Guiscriff",
        "Hanvec",
        "Hôpital-Camfrout",
        "Île-Tudy",
        "Kerlaz",
        "La Forêt-Fouesnant",
        "Landeleau",
        "Landévennec",
        "Landrévarzec",
        "Landudal",
        "Landudec",
        "Langolen",
        "Lannédern",
        "Laz",
        "Le Cloître-Pleyben",
        "Le Faou",
        "Le Juch",
        "Le Trévoux",
        "Lennon",
        "Leuhan",
        "Locronan",
        "Loctudy",
        "Logonna-Daoulas",
        "Lopérec",
        "Lothey",
        "Mahalon",
        "Melgven",
        "Névez",
        "Penmarch",
        "Peumerit",
        "Pleuven",
        "Pleyben",
        "Plobannalec-Lesconil",
        "Ploéven",
        "Plogastel-Saint-Germain",
        "Plogonnec",
        "Plomelin",
        "Plomeur",
        "Plomodiern",
        "Plonéis",
        "Plonéour-Lanvern",
        "Plonévez-du-Faou",
        "Plonévez-Porzay",
        "Plouhinec",
        "Plovan",
        "Plozévet",
        "Pluguffan",
        "Pont-Aven",
        "Pont-Croix",
        "Pont-de-Buis-lès-Quimerch",
        "Pont-l'Abbé",
        "Port-Launay",
        "Pouldergat",
        "Pouldreuzic",
        "Poullan-sur-Mer",
        "Primelin",
        "Quéménéven",
        "Quimper",
        "Riec-sur-Bélon",
        "Rosnoën",
        "Rosporden",
        "Roudouallec",
        "Saint-Coulitz",
        "Saint-Évarzec",
        "Saint-Goazec",
        "Saint-Jean-Trolimon",
        "Saint-Nic",
        "Saint-Ségal",
        "Saint-Thois",
        "Saint-Thurien",
        "Saint-Yvi",
        "Scaër",
        "Spézet",
        "Telgruc-sur-Mer",
        "Tourch",
        "Treffiagat",
        "Trégarvan",
        "Trégourez",
        "Tréguennec",
        "Trégunc",
        "Tréméoc",
        "Tréogat",
    ]
}

vannes = {
    "departements" : ['56', '29', '22', '35', '44'],
    "communes": [
        "Ambon",
        "Arradon",
        "Arzon",
        "Auray",
        "Baden",
        "Baud",
        "Belz",
        "Berric",
        "Bignan",
        "Billiers",
        "Billio",
        "Bohal",
        "Bono",
        "Brandérion",
        "Brandivy",
        "Brech",
        "Buléon",
        "Caden",
        "Camors",
        "Carnac",
        "Caro",
        "Colpo",
        "Crach",
        "Cruguel",
        "Damgan",
        "Elven",
        "Erdeven",
        "Étel",
        "Évellys",
        "Grand-Champ",
        "Guégon",
        "Guéhenno",
        "Guénin",
        "Guillac",
        "Hœdic",
        "Île-aux-Moines",
        "Île-d'Arz",
        "Île-d'Houat",
        "Josselin",
        "Kervignac",
        "La Chapelle-Neuve",
        "La Croix-Helléan",
        "La Trinité-sur-Mer",
        "La Trinité-Surzur",
        "La Vraie-Croix",
        "Landaul",
        "Landévant",
        "Languidic",
        "Lantillac",
        "Larmor-Baden",
        "Larré",
        "Lauzach",
        "Le Cours",
        "Le Guerno",
        "Le Hézo",
        "Le Tour-du-Parc",
        "Limerzel",
        "Lizio",
        "Locmaria-Grand-Champ",
        "Locmariaquer",
        "Locminé",
        "Locoal-Mendon",
        "Locqueltas",
        "Malansac",
        "Malestroit",
        "Merlevenez",
        "Meucon",
        "Missiriac",
        "Molac",
        "Monterblanc",
        "Montertelot",
        "Moréac",
        "Moustoir-Ac",
        "Muzillac",
        "Nostang",
        "Noyal-Muzillac",
        "Péaule",
        "Pénestin",
        "Plaudren",
        "Plescop",
        "Pleucadeuc",
        "Pleugriffet",
        "Ploemel",
        "Ploeren",
        "Plougoumelen",
        "Plouharnel",
        "Plouhinec",
        "Pluherlin",
        "Plumelec",
        "Pluméliau-Bieuzy",
        "Plumelin",
        "Plumergat",
        "Pluneret",
        "Pluvigner",
        "Questembert",
        "Quiberon",
        "Quistinic",
        "Radenac",
        "Réguiny",
        "Rochefort-en-Terre",
        "Ruffiac",
        "Saint-Abraham",
        "Saint-Allouestre",
        "Saint-Armel",
        "Saint-Avé",
        "Saint-Barthélemy",
        "Saint-Congard",
        "Sainte-Anne-d'Auray",
        "Sainte-Hélène",
        "Saint-Gildas-de-Rhuys",
        "Saint-Gorgon",
        "Saint-Gravé",
        "Saint-Guyomard",
        "Saint-Jean-Brévelay",
        "Saint-Laurent-sur-Oust",
        "Saint-Marcel",
        "Saint-Martin-sur-Oust",
        "Saint-Nolff",
        "Saint-Philibert",
        "Saint-Pierre-Quiberon",
        "Saint-Servant",
        "Sarzeau",
        "Séné",
        "Sérent",
        "Sulniac",
        "Surzur",
        "Theix-Noyalo",
        "Trédion",
        "Treffléan",
        "Val d'Oust",
        "Vannes",
    ]
}

rennes = {
    "departements": ['22', '35', '44', '56'],
    "communes": [
        "Acigné",
        "Amanlis",
        "Andouillé-Neuville",
        "Arbrissel",
        "Aubigné",
        "Bain-de-Bretagne",
        "Bais",
        "Baulon",
        "Bazouges-la-Pérouse",
        "Bécherel",
        "Bédée",
        "Betton",
        "Billé",
        "Bléruais",
        "Boisgervilly",
        "Boistrudan",
        "Bourgbarré",
        "Bourg-des-Comptes",
        "Bovel",
        "Bréal-sous-Montfort",
        "Brécé",
        "Breteil",
        "Brie",
        "Bruz",
        "Cardroc",
        "Cesson-Sévigné",
        "Champeaux",
        "Chanteloup",
        "Chantepie",
        "Chartres-de-Bretagne",
        "Chasné-sur-Illet",
        "Châteaubourg",
        "Châteaugiron",
        "Chauvigné",
        "Chavagne",
        "Chevaigné",
        "Cintré",
        "Clayes",
        "Coësmes",
        "Combourg",
        "Combourtillé",
        "Concoret",
        "Cornillé",
        "Corps-Nuds",
        "Crevin",
        "Cuguen",
        "Dingé",
        "Domagné",
        "Domalain",
        "Domloup",
        "Dourdain",
        "Drouges",
        "Ercé-en-Lamée",
        "Ercé-près-Liffré",
        "Essé",
        "Évran",
        "Feins",
        "Gahard",
        "Gévezé",
        "Gosné",
        "Goven",
        "Guenroc",
        "Guichen",
        "Guignen",
        "Guipel",
        "Guipry-Messac",
        "Guitté",
        "Hédé-Bazouges",
        "Iffendic",
        "Irodouër",
        "Janzé",
        "La Baussaine",
        "La Bosse-de-Bretagne",
        "La Bouëxière",
        "La Chapelle du Lou du Lac",
        "La Chapelle-aux-Filtzméens",
        "La Chapelle-Blanche",
        "La Chapelle-Bouëxic",
        "La Chapelle-Chaussée",
        "La Chapelle-des-Fougeretz",
        "La Chapelle-Saint-Aubert",
        "La Chapelle-Thouarault",
        "La Couyère",
        "La Dominelais",
        "La Mézière",
        "La Noë-Blanche",
        "La Nouaye",
        "Laillé",
        "Lalleu",
        "Landavran",
        "Landujan",
        "Langan",
        "Langouet",
        "Lanrigan",
        "Lassy",
        "Le Crouais",
        "Le Petit-Fougeray",
        "Le Quiou",
        "Le Rheu",
        "Le Sel-de-Bretagne",
        "Le Theil-de-Bretagne",
        "Le Tiercent",
        "Le Verger",
        "Les Brulais",
        "Les Iffs",
        "L'Hermitage",
        "Lieuron",
        "Liffré",
        "Livré-sur-Changeon",
        "Lohéac",
        "Longaulnay",
        "Lourmais",
        "Loutehel",
        "Louvigné-de-Bais",
        "Marcillé-Raoul",
        "Marcillé-Robert",
        "Marpiré",
        "Maxent",
        "Mecé",
        "Médréac",
        "Meillac",
        "Melesse",
        "Mernel",
        "Mézières-sur-Couesnon",
        "Miniac-sous-Bécherel",
        "Montauban-de-Bretagne",
        "Monterfil",
        "Montfort-sur-Meu",
        "Montgermont",
        "Montreuil-des-Landes",
        "Montreuil-le-Gast",
        "Montreuil-sous-Pérouse",
        "Montreuil-sur-Ille",
        "Mordelles",
        "Mouazé",
        "Moulins",
        "Moussé",
        "Muel",
        "Nouvoitou",
        "Noyal-Châtillon-sur-Seiche",
        "Noyal-sous-Bazouges",
        "Noyal-sur-Vilaine",
        "Orgères",
        "Pacé",
        "Paimpont",
        "Pancé",
        "Parcé",
        "Parthenay-de-Bretagne",
        "Pipriac",
        "Piré-Chancé",
        "Pléchâtel",
        "Plélan-le-Grand",
        "Plesder",
        "Pleugueneuc",
        "Pleumeleuc",
        "Plouasne",
        "Pocé-les-Bois",
        "Poligné",
        "Pont-Péan",
        "Québriac",
        "Quédillac",
        "Rannée",
        "Rennes",
        "Retiers",
        "Rimou",
        "Rives-du-Couesnon",
        "Romagné",
        "Romazy",
        "Romillé",
        "Saint-André-des-Eaux",
        "Saint-Armel",
        "Saint-Aubin-d'Aubigné",
        "Saint-Aubin-des-Landes",
        "Saint-Aubin-du-Cormier",
        "Saint-Brieuc-des-Iffs",
        "Saint-Christophe-des-Bois",
        "Saint-Christophe-de-Valains",
        "Saint-Didier",
        "Saint-Domineuc",
        "Sainte-Colombe",
        "Saint-Erblon",
        "Saint-Germain-du-Pinel",
        "Saint-Germain-sur-Ille",
        "Saint-Gilles",
        "Saint-Gondran",
        "Saint-Gonlay",
        "Saint-Grégoire",
        "Saint-Hilaire-des-Landes",
        "Saint-Jacques-de-la-Lande",
        "Saint-Jean-sur-Vilaine",
        "Saint-Jouan-de-l'Isle",
        "Saint-Judoce",
        "Saint-Juvat",
        "Saint-Léger-des-Prés",
        "Saint-Maden",
        "Saint-Malo-de-Beignon",
        "Saint-Malo-de-Phily",
        "Saint-Malon-sur-Mel",
        "Saint-Marc-le-Blanc",
        "Saint-Maugan",
        "Saint-Médard-sur-Ille",
        "Saint-Méen-le-Grand",
        "Saint-Onen-la-Chapelle",
        "Saint-Ouen-des-Alleux",
        "Saint-Péran",
        "Saint-Pern",
        "Saint-Rémy-du-Plain",
        "Saint-Sauveur-des-Landes",
        "Saint-Séglin",
        "Saint-Senoux",
        "Saint-Sulpice-des-Landes",
        "Saint-Sulpice-la-Forêt",
        "Saint-Symphorien",
        "Saint-Thual",
        "Saint-Thurial",
        "Saint-Uniac",
        "Saulnières",
        "Sens-de-Bretagne",
        "Servon-sur-Vilaine",
        "Soulvache",
        "Taillis",
        "Talensac",
        "Teillay",
        "Thorigné-Fouillard",
        "Thourie",
        "Tinténiac",
        "Torcé",
        "Treffendel",
        "Tréfumel",
        "Trémeheuc",
        "Tresbœuf",
        "Trévérien",
        "Trimer",
        "Val d'Anast",
        "Val-d'Izé",
        "Vergéal",
        "Vern-sur-Seiche",
        "Vezin-le-Coquet",
        "Vieux-Vy-sur-Couesnon",
        "Vignoc",
        "Visseiche",
        "Vitré",
    ]
}

le_havre = {
    "departements": ['76', '27', '50', '14'],
    "communes": [
        "Ablon",
        "Amfreville",
        "Angerville",
        "Annebault",
        "Auberville",
        "Les Authieux-sur-Calonne",
        "Auvillars",
        "Barneville-la-Bertran",
        "Basseneville",
        "Bavent",
        "Beaumont-en-Auge",
        "Benerville-sur-Mer",
        "Bénouville",
        "Beuvron-en-Auge",
        "Blangy-le-Château",
        "Blonville-sur-Mer",
        "Bonnebosq",
        "Bonneville-la-Louvet",
        "Bonneville-sur-Touques",
        "Bourgeauville",
        "Branville",
        "Le Breuil-en-Auge",
        "Le Brévedent",
        "Bréville-les-Monts",
        "Brucourt",
        "Cabourg",
        "Cambremer",
        "Canapville",
        "Clarbec",
        "Colleville-Montgomery",
        "Coquainvilliers",
        "Cresseveuille",
        "Cricquebœuf",
        "Cricqueville-en-Auge",
        "Danestal",
        "Deauville",
        "Dives-sur-Mer",
        "Douville-en-Auge",
        "Dozulé",
        "Drubec",
        "Beaufour-Druval",
        "Englesqueville-en-Auge",
        "Équemauville",
        "Fauguernon",
        "Le Faulq",
        "Fierville-les-Parcs",
        "Formentin",
        "Le Fournet",
        "Fourneville",
        "Genneville",
        "Gerrots",
        "Glanville",
        "Gonneville-sur-Honfleur",
        "Gonneville-sur-Mer",
        "Gonneville-en-Auge",
        "Goustranville",
        "Grangues",
        "Hermanville-sur-Mer",
        "Hermival-les-Vaux",
        "Heuland",
        "Honfleur",
        "Hotot-en-Auge",
        "Houlgate",
        "Léaupartie",
        "Lion-sur-Mer",
        "Luc-sur-Mer",
        "Manerbe",
        "Manneville-la-Pipard",
        "Merville-Franceville-Plage",
        "Le Mesnil-sur-Blangy",
        "Montreuil-en-Auge",
        "Moyaux",
        "Norolles",
        "Ouilly-le-Vicomte",
        "Ouistreham",
        "Pennedepie",
        "Périers-en-Auge",
        "Petiville",
        "Pierrefitte-en-Auge",
        "Le Pin",
        "Pont-l'Évêque",
        "Le Pré-d'Auge",
        "Putot-en-Auge",
        "Quetteville",
        "Ranville",
        "Repentigny",
        "Reux",
        "La Rivière-Saint-Sauveur",
        "Rocques",
        "La Roque-Baignard",
        "Rumesnil",
        "Saint-André-d'Hébertot",
        "Saint-Arnoult",
        "Saint-Aubin-d'Arquenay",
        "Saint-Benoît-d'Hébertot",
        "Saint-Étienne-la-Thillaye",
        "Saint-Gatien-des-Bois",
        "Saint-Hymer",
        "Saint-Jouin",
        "Saint-Julien-sur-Calonne",
        "Saint-Léger-Dubosq",
        "Saint-Martin-aux-Chartrains",
        "Saint-Ouen-le-Pin",
        "Saint-Philbert-des-Champs",
        "Saint-Pierre-Azif",
        "Saint-Vaast-en-Auge",
        "Sallenelles",
        "Surville",
        "Le Theil-en-Auge",
        "Le Torquesne",
        "Touques",
        "Tourgéville",
        "Tourville-en-Auge",
        "Trouville-sur-Mer",
        "Valsemé",
        "Varaville",
        "Vauville",
        "Victot-Pontfol",
        "Vieux-Bourg",
        "Villers-sur-Mer",
        "Villerville",
        "Aizier",
        "Asnières",
        "Berville-sur-Mer",
        "Beuzeville",
        "Le Bois-Hellain",
        "Boulleville",
        "Bouquelon",
        "Bourneville-Sainte-Croix",
        "Campigny",
        "La Chapelle-Bayvel",
        "Conteville",
        "Cormeilles",
        "Corneville-sur-Risle",
        "Épaignes",
        "Fatouville-Grestain",
        "Fiquefleur-Équainville",
        "Fort-Moville",
        "Foulbec",
        "Le Perrey",
        "La Lande-Saint-Léger",
        "Manneville-la-Raoult",
        "Manneville-sur-Risle",
        "Marais-Vernier",
        "Martainville",
        "Morainville-Jouveaux",
        "La Noë-Poulain",
        "Pont-Audemer",
        "La Poterie-Mathieu",
        "Les Préaux",
        "Quillebeuf-sur-Seine",
        "Saint-Aubin-sur-Quillebeuf",
        "Saint-Maclou",
        "Saint-Mards-de-Blacarville",
        "Sainte-Opportune-la-Mare",
        "Saint-Pierre-de-Cormeilles",
        "Saint-Pierre-du-Val",
        "Saint-Samson-de-la-Roque",
        "Saint-Siméon",
        "Saint-Sulpice-de-Grimbouville",
        "Saint-Sylvestre-de-Cormeilles",
        "Saint-Symphorien",
        "Selles",
        "Tocqueville",
        "Le Torpt",
        "Tourville-sur-Pont-Audemer",
        "Toutainville",
        "Triqueville",
        "Trouville-la-Haule",
        "Vannecrocq",
        "Vieux-Port",
        "Angerville-Bailleul",
        "Angerville-l'Orcher",
        "Anglesqueville-l'Esneval",
        "Annouville-Vilmesnil",
        "Anquetierville",
        "Auberville-la-Renault",
        "Beaurepaire",
        "Bec-de-Mortagne",
        "Bénarville",
        "Bénouville",
        "Bernières",
        "Beuzeville-la-Grenier",
        "Beuzevillette",
        "Bolbec",
        "Bolleville",
        "Bordeaux-Saint-Clair",
        "Bornambusc",
        "Bréauté",
        "Bretteville-du-Grand-Caux",
        "Cauville-sur-Mer",
        "La Cerlangue",
        "Cléville",
        "Colleville",
        "Contremoulins",
        "Criquebeuf-en-Caux",
        "Criquetot-l'Esneval",
        "Cuverville",
        "Daubeuf-Serville",
        "Écrainville",
        "Épouville",
        "Épretot",
        "Épreville",
        "Étainhus",
        "Étretat",
        "Terres-de-Caux",
        "Fécamp",
        "Fongueusemare",
        "Fontaine-la-Mallet",
        "Fontenay",
        "Foucart",
        "La Frénaye",
        "Froberville",
        "Gainneville",
        "Ganzeville",
        "Gerville",
        "Goderville",
        "Gommerville",
        "Gonfreville-Caillot",
        "Gonfreville-l'Orcher",
        "Gonneville-la-Mallet",
        "Graimbouville",
        "Grainville-Ymauville",
        "Grand-Camp",
        "Gruchet-le-Valasse",
        "Harfleur",
        "Hattenville",
        "Le Havre",
        "Hermeville",
        "Heuqueville",
        "Houquetot",
        "Lanquetot",
        "Lillebonne",
        "Limpiville",
        "Lintot",
        "Les Loges",
        "Manéglise",
        "Maniquerville",
        "Manneville-la-Goupil",
        "Mannevillette",
        "Mélamare",
        "Mentheville",
        "Mirville",
        "Montivilliers",
        "Nointot",
        "Norville",
        "Port-Jérôme-sur-Seine",
        "Notre-Dame-du-Bec",
        "Octeville-sur-Mer",
        "Oudalle",
        "Parc-d'Anxtot",
        "Petiville",
        "Pierrefiques",
        "La Poterie-Cap-d'Antifer",
        "Raffetot",
        "La Remuée",
        "Rogerville",
        "Rolleville",
        "Rouville",
        "Sainneville",
        "Sainte-Adresse",
        "Saint-Antoine-la-Forêt",
        "Saint-Aubin-de-Crétot",
        "Saint-Aubin-Routot",
        "Saint-Eustache-la-Forêt",
        "Saint-Gilles-de-Crétot",
        "Saint-Gilles-de-la-Neuville",
        "Saint-Jean-de-Folleville",
        "Saint-Jean-de-la-Neuville",
        "Saint-Jouin-Bruneval",
        "Saint-Laurent-de-Brèvedent",
        "Saint-Léonard",
        "Saint-Maclou-la-Brière",
        "Sainte-Marie-au-Bosc",
        "Saint-Martin-du-Bec",
        "Saint-Martin-du-Manoir",
        "Saint-Maurice-d'Ételan",
        "Saint-Nicolas-de-la-Haie",
        "Saint-Nicolas-de-la-Taille",
        "Saint-Romain-de-Colbosc",
        "Saint-Sauveur-d'Émalleville",
        "Saint-Vigor-d'Ymonville",
        "Saint-Vincent-Cramesnil",
        "Sandouville",
        "Sausseuzemare-en-Caux",
        "Senneville-sur-Fécamp",
        "Tancarville",
        "Thiergeville",
        "Thiétreville",
        "Le Tilleul",
        "Tocqueville-les-Murs",
        "Tourville-les-Ifs",
        "Toussaint",
        "Trémauville",
        "La Trinité-du-Mont",
        "Les Trois-Pierres",
        "Trouville",
        "Turretot",
        "Vattetot-sous-Beaumont",
        "Vattetot-sur-Mer",
        "Vergetot",
        "Villainville",
        "Virville",
        "Yébleron",
        "Yport",
        "Ypreville-Biville",
    ]
}