"""Changement objectif

Revision ID: a64307cd3c69
Revises: 7739c55cf576
Create Date: 2023-11-08 14:55:56.245601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64307cd3c69'
down_revision = '7739c55cf576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('newsletter', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter', 'updated_at')
    op.drop_column('newsletter', 'created_at')
    # ### end Alembic commands ###
