import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://recosante.beta.gouv.fr/',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/a-quelle-periode-de-l-annee-y-a-t-il-le-plus-de-pollen-dans-l-air',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/a-velo-comment-reduire-son-exposition-a-la-pollution',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/chauffage-au-bois-comment-bien-l-utiliser',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-adapter-sa-pratique-sportive-selon-la-qualite-de-l-air',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-aerer-son-logement-pour-ameliorer-l-air-interieur',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-agir-la-france-sur-la-pollution-atmospherique',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-ameliorer-l-air-de-son-logement-quand-on-est-futurs-ou-nouveaux-parents',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-ameliorer-la-qualite-de-l-air-chez-soi-grace-a-la-ventilation',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-chauffer-son-interieur-en-toute-securite',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-choisir-et-utiliser-un-produit-de-protection-solaire',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-eviter-l-exposition-a-l-amiante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-eviter-les-morsures-de-tiques',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-eviter-une-intoxication-au-monoxyde-de-carbone',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-jardiner-sans-polluer',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-la-meteo-influence-t-elle-la-qualite-de-l-air',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-limiter-l-humidite-dans-son-logement',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-limiter-la-presence-d-acariens-dans-son-logement',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-limiter-les-effets-du-bruit-sur-la-sante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-lutter-contre-les-punaises-de-lit',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-prevenir-l-exposition-au-plomb-dans-son-logement',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-proteger-son-enfant-des-produits-chimiques-a-la-maison',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-proteger-votre-sante-et-celle-de-vos-enfants-en-cas-de-fortes-chaleurs',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-reconnaitre-une-allergie-aux-pollens',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-reduire-l-exposition-aux-ondes-de-son-telephone-portable',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-reduire-l-exposition-aux-perturbateurs-endocriniens',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-reduire-l-exposition-aux-polluants-pendant-les-travaux',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-reduire-les-effets-des-pollens-sur-votre-sante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-se-proteger-du-moustique-tigre',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-se-proteger-en-cas-de-vague-de-chaleur',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/comment-utiliser-l-eau-de-pluie',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/covid-19-quels-gestes-adopter-pour-proteger-sa-sante-et-son-environnement',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/cueillette-de-champignons-comment-prevenir-les-intoxications',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/cuisiner-en-protegeant-sa-sante-quels-gestes-adopter',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/inondations-quels-sont-les-bons-reflexes',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/l-air-interieur-des-logements-est-il-pollue',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-bougies-et-l-encens-degradent-ils-la-qualite-de-l-air-interieur',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-microcapteurs-de-qualite-de-l-air-ambiant-sont-ils-fiables',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-plantes-ameliorent-elles-la-qualite-de-l-air-interieur',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-produits-d-entretien-polluent-ils-l-air-interieur',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-purificateurs-d-air-ameliorent-ils-la-qualite-de-l-air-interieur-chez-soi',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-rayons-uv-quels-effets-sur-la-sante-et-celle-de-vos-enfants',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/les-rayons-uv-quels-effets-sur-la-sante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/pollution-de-l-air-en-voiture-comment-la-limiter',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/pollution-de-l-air-et-sante-quels-liens',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/pollution-des-sols-liee-a-l-activite-humaine-quels-effets-sur-la-sante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/pourquoi-faut-il-lutter-contre-l-ambroisie',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/qu-est-ce-que-la-vigilance-meteorologique',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/que-faire-en-cas-de-vigilance-meteo-neige-et-verglas',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/que-faire-en-presence-de-radon-dans-son-logement',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/que-signifient-les-pictogrammes-de-danger-sur-les-produits-chimiques',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quel-est-le-role-des-transports-dans-la-pollution-atmospherique',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-comportements-adopter-en-cas-de-secheresse',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-gestes-adopter-en-cas-de-vigilance-meteo-avalanche',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-gestes-adopter-en-periode-de-grand-froid',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-gestes-adopter-pour-profiter-du-sapin-de-noel-en-toute-securite-a-la-maison',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-reflexes-a-prendre-pour-proteger-son-enfant-du-grand-froid',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/quels-sont-les-effets-de-la-lumiere-bleue-sur-la-sante',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://recosante.beta.gouv.fr/articles/rayons-uv-lies-au-soleil-quels-risques-pour-les-yeux',
      lastModified: '2024-03-07',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
  ];
}
